[gcp]
    [gcp.prod]
    project_id = "dataverbinders"
    bucket = "dataverbinders"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.

    [gcp.test]
    project_id = "dataverbinders-test"
    bucket = "dataverbinders-test"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.

    [gcp.dev]
    project_id = "dataverbinders-dev"
    bucket = "dataverbinders-dev"
    location = "EU"
    # credentials = ""  # currently not taken here. User needs to have authentication setup previous to using this library.
                        # see "https://cloud.google.com/docs/authentication/end-user" for instructions if issues occur with authentication.
    
[paths]
# Temporary paths to use for transformations are defined here.

root = "Projects/statline-bq"  # DEFINE PATH TO LIBRARY HERE

# All data paths are relative to "Path.home()/root"
temp = "temp"
cbs = "cbs"