# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ..service_mesh_probe import service_mesh_pb2 as service__mesh__probe_dot_service__mesh__pb2


class ServiceMeshMetricServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.collect = channel.stream_unary(
                '/ServiceMeshMetricService/collect',
                request_serializer=service__mesh__probe_dot_service__mesh__pb2.ServiceMeshMetric.SerializeToString,
                response_deserializer=service__mesh__probe_dot_service__mesh__pb2.MeshProbeDownstream.FromString,
                )


class ServiceMeshMetricServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def collect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceMeshMetricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'collect': grpc.stream_unary_rpc_method_handler(
                    servicer.collect,
                    request_deserializer=service__mesh__probe_dot_service__mesh__pb2.ServiceMeshMetric.FromString,
                    response_serializer=service__mesh__probe_dot_service__mesh__pb2.MeshProbeDownstream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceMeshMetricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceMeshMetricService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def collect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ServiceMeshMetricService/collect',
            service__mesh__probe_dot_service__mesh__pb2.ServiceMeshMetric.SerializeToString,
            service__mesh__probe_dot_service__mesh__pb2.MeshProbeDownstream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
