[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-grid<=0.2.0.dev20201218', 'dune-localfunctions<=0.2.0.dev20201218']
build-backend = 'setuptools.build_meta'
