
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-22T12:02:53-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "44e192c5ba6bb096902ea4e1aac5e99fd7fb8b71",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
