site_name: aws-gate
site_description: AWS SSM Session manager CLI client
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
nav:
  - Introduction:
      - aws-gate: index.md
      - License: license.md
      - Changelog: changelog.md
  - Quickstart: quickstart.md
  - Configuration: configuration.md
  - Command Line: command-line.md
  - Development: development.md
