[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "terra-sdk"
version = "0.0.2"
description = "The Python SDK for Terra"
authors = ["Terraform Labs, PTE. <engineering@terra.money>"]
readme = "README.md"
repository = "https://github.com/terra-project/terra-sdk-python"

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^20.3.0"
tabulate = "^0.8.7"
requests = "^2.25.0"
requests-futures = "^1.0.0"
bech32 = "^1.2.0"
bip32utils = "^0.3.post4"
cached-property = "^1.5.2"
mnemonic = "^0.19"
Sphinx = "^3.4.0"
sphinx-rtd-theme = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
black = "^20.8b1"
pylint = "^2.6.0"
mypy = "^0.790"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "integration-tests",
]