# Generated by Django 3.0.11 on 2020-12-20 18:41

import djangelo._elo_implementation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELORated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(editable=False, null=True)),
                ('hints', models.IntegerField(default=0, editable=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(djangelo._elo_implementation.ELOComparator, djangelo._elo_implementation.ELOAlgorithmImplementation, models.Model),
        ),
    ]
