# Generated by Django 3.0.11 on 2020-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elorated',
            name='value',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
