[tool.pdm]
name = "pdm"
version = "0.12.3"
description = "Python Development Master"
author = "frostming <mianghong@gmail.com>"
license = "MIT"
python_requires = ">=3.7"
readme = "README.md"
homepage = "https://pdm.fming.dev"

keywords = ["packaging", "dependency", "workflow"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9"
]

[tool.pdm.project_urls]
Repository = "https://github.com/frostming/pdm"
Documentation = "https://pdm.fming.dev"

[tool.pdm.dependencies]
appdirs = "*"
click = "*"
distlib = "*"
importlib-metadata = {version = "*", marker = "python_version<'3.8'"}
pdm-pep517 = "<0.3.0,>=0.1.0"
pep517 = "*"
pip = ">=20.1,<21"
pycomplete = "<1.0.0,>=0.2.0"
python-cfonts = "*"
python-dotenv = "<1.0.0,>=0.15.0"
pythonfinder = "*"
resolvelib = "<1.0.0,>=0.3.0"
shellingham = "<2.0.0,>=1.3.2"
tomlkit = "*"
wheel = "<1.0.0,>=0.36.2"

[tool.pdm.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
towncrier = "<20.0.0,>=19.2.0"
pytest-xdist = "<2.0.0,>=1.31.0"
vendoring = {version = "*", marker = "python_version ~= '3.8'"}
parver = "<1.0.0,>=0.3.1"

[tool.pdm.doc-dependencies]
mkdocs = "<2.0.0,>=1.1"
mkdocs-material = "<5.0.0,>=4.6.3"
markdown-include = "<1.0.0,>=0.5.1"

[tool.pdm.cli]
pdm = "pdm.core:main"

[tool.pdm.scripts]
release = "python tasks/release.py"

[tool.black]
line-length = 88
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | pdm/_vendor/*
)/
'''

[tool.towncrier]
package = "pdm"
filename = "CHANGELOG.md"
issue_format = "[#{issue}](https://github.com/frostming/pdm/issues/{issue})"
directory = "news/"
title_format = "Release v{version} ({project_date})"
template = "news/towncrier_template.md"
underlines = "-~^"

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features & Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "doc"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "dep"
  name = "Dependencies"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "removal"
  name = "Removals and Deprecations"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "misc"
  name = "Miscellany"
  showcontent = true

[build-system]
requires = ["pdm-pep517<0.3.0"]
build-backend = "pdm.pep517.api"

[tool.isort]
profile = "black"
atomic = true
skip_glob = ["*/setup.py", "pdm/_vendor/*"]
filter_files = true
known_first_party = ["pdm"]
known_third_party = [
    "click",
    "halo",
    "distlib",
    "pythonfinder",
    "pytest",
    "tomlkit",
    "appdirs",
    "pip_shims",
    "cfonts",
    "packaging",
]

[tool.vendoring]
destination = "pdm/_vendor/"
requirements = "pdm/_vendor/vendors.txt"
namespace = "pdm._vendor"

protected-files = ["__init__.py", "README.md", "vendors.txt"]
patches-dir = "tasks/patches"

[tool.vendoring.transformations]
substitute = [
  {match = 'import halo\.', replace = 'import pdm._vendor.halo.'}
]
drop = [
    "bin/",
    "*.so",
    "typing.*",
    "*/tests/"
]

[tool.vendoring.typing-stubs]
halo = []
log_symbols = []
spinners = []
termcolor = []
colorama = []

[tool.vendoring.license.directories]

[tool.vendoring.license.fallback-urls]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning"
]
markers = ["pypi: Tests that connect to the real PyPI"]
