[tool.poetry]
name = "ml-python-lib"
version = "0.2.0"
description = "Machine Learning Library for tensorflow training algorithms"
authors = ["Tanguy Coatalem <tanguy.coatalem@cogneed.ai>"]

[tool.poetry.dependencies]
python = "^3.6"
keyring = "^21.5.0"
tensorflow = "^2.3.1"
dynaconf = "^3.1.2"
pydub = "^0.24.1"

[tool.poetry.dev-dependencies]
coverage = "^5.3"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
