image: michaellundquist/rmtoobase:latest

# to make this faster, setup a custom runner for it (and tag it) that caches the image

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - /var/cache/apt/archives/
    - ./downloads

createArtifacts:
    stage: build
    #tags: rmtoo #add this in when you create a custom runner
    script:
        - make clean
        - make
        - ls artifacts
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - ./artifacts/*
        expire_in: 3 weeks and 2 days
