[tool.poetry]
name = "lime-etl"
version = "0.1.27"
description = "Simple ETL job runner"
authors = ["Mark Stefanovic"]
include = ["lime_etl/py.typed"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8.0"
sqlalchemy = "^1.3.19"
lime-uow = "^0.1.43"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"
mypy = "^0.790"
sqlalchemy-stubs = "^0.3"
psycopg2-binary = "^2.8.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
