name: wilfred
base: core18
version: 'v0.8.0' # set version on release ('v0.1.0') and use 'git' during dev
summary: A CLI for managing game servers using Docker # 79 char long summary
description: |
  Wilfred is a command-line interface for running game servers locally. It uses Docker to run game servers in containers, which means they are completely separated. Wilfred can run any game that can run in Docker.

  Wilfred is currently under development and should not be considered stable. Features may break or may not be implemented yet. Use with caution.

grade: devel # 'stable' on release ('devel' during dev)
confinement: devmode # should be 'classic' once we have the classic confinement approved

#plugs:
#  docker:
#    content: docker
#    default-provider: docker
#    interface: content
#    target: docker-env
#  network:

parts:
  wilfred:
    override-build: |
      sed -i "s/development/`git log -1 --format="%H"`/g" wilfred/version.py
      sed -i "s/YYYY-MM-DD/`git log -1 --format="%at" | xargs -I{} date -d @{} +%Y-%m-%d`/g" wilfred/version.py
      snapcraftctl build
    plugin: python
    source: .
    build-packages:
      - python3-distutils
      - build-essential

apps:
  wilfred:
    command: bin/wilfred
    # plugs: [docker, network]
    environment:
      PYTHONIOENCODING: utf-8
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
