[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120

[tool.isort]
combine_as_imports = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
profile = "black"
use_parentheses = true

[tool.poetry]
name = "dvtv-dl"
version = "0.1.1"
description = ""
authors = ["Jakub Dorňák <jakub.dornak@misli.cz>"]
license = "BSD-3-Clause"
readme = "README.rst"
repository = "https://github.com/misli/dvtv-dl"

[tool.poetry.dependencies]
feedparser = "^6.0.2"
python = "^3.8"
youtube_dl = "^2020.12.29"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"

[tool.poetry.scripts]
dvtv-dl = 'dvtv_dl:main'

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
