[tool.poetry]
name = "toggl_python"
version = "0.2.7"
description = "Python wrapper for Toggl API."
authors = ["Ivlev Denis <me@dierz.pro>"]
readme = "README.md"
homepage = "https://github.com/evrone/toggl_python"
repository = "https://github.com/evrone/toggl_python"
documentation = "https://toggl-python.readthedocs.io"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras=["http2"], version="^0.16.1"}
pydantic = {extras = ["email"], version = "^1.7.2"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
respx = "^0.16"
black = "^20.8b1"
ipython = "^7.19.0"
mypy = "^0.790"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
