[tool.poetry]
name = "verval"
version = "0.1.0"
description = "Client python verval* sdm.data.kemdikbud"
authors = ["hexatester <habibrohman@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage = "https://github.com/dapodix/verval"
repository = "https://github.com/dapodix/verval"
packages = [
    { include = "verval" },
]
include = [
    "LICENSE",
    "README.md",
]


[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
bs4 = "^0.0.1"
dacite = "^1.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
mypy = "^0.790"
pre-commit = "^2.9.3"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
