# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _depth_first_bnb
else:
    import _depth_first_bnb

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _depth_first_bnb.delete_SwigPyIterator

    def value(self):
        return _depth_first_bnb.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _depth_first_bnb.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _depth_first_bnb.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _depth_first_bnb.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _depth_first_bnb.SwigPyIterator_equal(self, x)

    def copy(self):
        return _depth_first_bnb.SwigPyIterator_copy(self)

    def next(self):
        return _depth_first_bnb.SwigPyIterator_next(self)

    def __next__(self):
        return _depth_first_bnb.SwigPyIterator___next__(self)

    def previous(self):
        return _depth_first_bnb.SwigPyIterator_previous(self)

    def advance(self, n):
        return _depth_first_bnb.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _depth_first_bnb.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _depth_first_bnb.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _depth_first_bnb.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _depth_first_bnb.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _depth_first_bnb.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _depth_first_bnb.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _depth_first_bnb:
_depth_first_bnb.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _depth_first_bnb.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _depth_first_bnb.IntVector___nonzero__(self)

    def __bool__(self):
        return _depth_first_bnb.IntVector___bool__(self)

    def __len__(self):
        return _depth_first_bnb.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _depth_first_bnb.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _depth_first_bnb.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _depth_first_bnb.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _depth_first_bnb.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _depth_first_bnb.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _depth_first_bnb.IntVector___setitem__(self, *args)

    def pop(self):
        return _depth_first_bnb.IntVector_pop(self)

    def append(self, x):
        return _depth_first_bnb.IntVector_append(self, x)

    def empty(self):
        return _depth_first_bnb.IntVector_empty(self)

    def size(self):
        return _depth_first_bnb.IntVector_size(self)

    def swap(self, v):
        return _depth_first_bnb.IntVector_swap(self, v)

    def begin(self):
        return _depth_first_bnb.IntVector_begin(self)

    def end(self):
        return _depth_first_bnb.IntVector_end(self)

    def rbegin(self):
        return _depth_first_bnb.IntVector_rbegin(self)

    def rend(self):
        return _depth_first_bnb.IntVector_rend(self)

    def clear(self):
        return _depth_first_bnb.IntVector_clear(self)

    def get_allocator(self):
        return _depth_first_bnb.IntVector_get_allocator(self)

    def pop_back(self):
        return _depth_first_bnb.IntVector_pop_back(self)

    def erase(self, *args):
        return _depth_first_bnb.IntVector_erase(self, *args)

    def __init__(self, *args):
        _depth_first_bnb.IntVector_swiginit(self, _depth_first_bnb.new_IntVector(*args))

    def push_back(self, x):
        return _depth_first_bnb.IntVector_push_back(self, x)

    def front(self):
        return _depth_first_bnb.IntVector_front(self)

    def back(self):
        return _depth_first_bnb.IntVector_back(self)

    def assign(self, n, x):
        return _depth_first_bnb.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _depth_first_bnb.IntVector_resize(self, *args)

    def insert(self, *args):
        return _depth_first_bnb.IntVector_insert(self, *args)

    def reserve(self, n):
        return _depth_first_bnb.IntVector_reserve(self, n)

    def capacity(self):
        return _depth_first_bnb.IntVector_capacity(self)
    __swig_destroy__ = _depth_first_bnb.delete_IntVector

# Register IntVector in _depth_first_bnb:
_depth_first_bnb.IntVector_swigregister(IntVector)

class Protein(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, sequence, dim=2):
        _depth_first_bnb.Protein_swiginit(self, _depth_first_bnb.new_Protein(sequence, dim))

    def get_sequence(self):
        return _depth_first_bnb.Protein_get_sequence(self)

    def get_dim(self):
        return _depth_first_bnb.Protein_get_dim(self)

    def get_cur_len(self):
        return _depth_first_bnb.Protein_get_cur_len(self)

    def get_last_pos(self):
        return _depth_first_bnb.Protein_get_last_pos(self)

    def get_amino(self, position):
        return _depth_first_bnb.Protein_get_amino(self, position)

    def get_score(self):
        return _depth_first_bnb.Protein_get_score(self)

    def get_changes(self):
        return _depth_first_bnb.Protein_get_changes(self)

    def get_h_idxs(self):
        return _depth_first_bnb.Protein_get_h_idxs(self)

    def is_hydro(self, index):
        return _depth_first_bnb.Protein_is_hydro(self, index)

    def reset(self):
        return _depth_first_bnb.Protein_reset(self)

    def reset_conformation(self):
        return _depth_first_bnb.Protein_reset_conformation(self)

    def is_valid(self, move):
        return _depth_first_bnb.Protein_is_valid(self, move)

    def place_amino(self, move, track=True):
        return _depth_first_bnb.Protein_place_amino(self, move, track)

    def remove_amino(self, move):
        return _depth_first_bnb.Protein_remove_amino(self, move)

    def change_score(self, move, value):
        return _depth_first_bnb.Protein_change_score(self, move, value)

    def hash_fold(self):
        return _depth_first_bnb.Protein_hash_fold(self)

    def set_hash(self, fold_hash, track=False):
        return _depth_first_bnb.Protein_set_hash(self, fold_hash, track)
    __swig_destroy__ = _depth_first_bnb.delete_Protein

# Register Protein in _depth_first_bnb:
_depth_first_bnb.Protein_swigregister(Protein)


def depth_first_bnb(protein):
    return _depth_first_bnb.depth_first_bnb(protein)


