[tool.poetry]
name = "wxltz"
version = "0.1.1"
description = ""
authors = ["givonwash <givonwash@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
waltz = "wxltz.main:app"

[tool.poetry.dependencies]
python = "^3.9"
pywal = "^3.3.0"
typer = {extras = ["all"], version = "^0.3.2"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
