[tool.poetry]
name = "rnm"
version = "0.2.0"
description = ""
authors = ["KhalidCK"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.0"
python-slugify = "^4.0.1"
beautifulsoup4 = "^4.9.3"
pydantic = "^1.7.3"
clean-text = {extras = ["gpl"], version = "^0.3.0"}
loguru = "^0.5.3"
pandas = "^1.1.5"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
jupyterlab = "^2.2.9"
black = {version = "^20.8b1", allow-prereleases = true}
bandit = "^1.7.0"
tox = "^3.20.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
