# Copyright (c) 2016 EMC Corporation.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

UnityDisk:
  - name: read_iops
    paths: sp.*.physical.disk.*.reads
  - name: write_iops
    paths: sp.*.physical.disk.*.writes
  - name: total_iops
    paths:
      - sp.*.physical.disk.*.reads
      - sp.*.physical.disk.*.writes
    calculator: total_delta_ps
  - name: read_mbps
    paths: sp.*.physical.disk.*.readBlocks
    calculator: mb_ps_by_block
  - name: write_mbps
    paths: sp.*.physical.disk.*.writeBlocks
    calculator: mb_ps_by_block
  - name: utilization
    paths:
      - sp.*.physical.disk.*.busyTicks
      - sp.*.physical.disk.*.idleTicks
    calculator: busy_idle_util
  - name: response_time
    paths:
      - sp.*.physical.disk.*.busyTicks
      - sp.*.physical.disk.*.sumArrivalQueueLength
      - sp.*.physical.disk.*.reads
      - sp.*.physical.disk.*.writes
      - sp.*.physical.coreCount
    calculator: disk_response_time
  - name: queue_length
    paths:
      - sp.*.physical.disk.*.sumArrivalQueueLength
      - sp.*.physical.disk.*.reads
      - sp.*.physical.disk.*.writes
    calculator: disk_queue_length
  - name: read_byte_rate
    paths:
      - sp.*.physical.disk.*.readBlocks
      - sp.*.physical.blockSize
    calculator: byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.physical.disk.*.writeBlocks
      - sp.*.physical.blockSize
    calculator: byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.physical.disk.*.readBlocks
      - sp.*.physical.disk.*.writeBlocks
      - sp.*.physical.blockSize
    calculator: total_byte_rate


UnityLun:
  - name: read_iops
    paths: sp.*.storage.lun.*.reads
  - name: write_iops
    paths: sp.*.storage.lun.*.writes
  - name: total_iops
    paths:
      - sp.*.storage.lun.*.reads
      - sp.*.storage.lun.*.writes
    calculator: total_delta_ps
  - name: read_mbps
    paths: sp.*.storage.lun.*.readBlocks
    calculator: mb_ps_by_block
  - name: write_mbps
    paths: sp.*.storage.lun.*.writeBlocks
    calculator: mb_ps_by_block
  - name: utilization
    paths:
      - sp.*.storage.lun.*.busyTime
      - sp.*.storage.lun.*.idleTime
    calculator: busy_idle_util
  - name: response_time
    paths:
      - sp.*.storage.lun.*.totalIoTime
      - sp.*.storage.lun.*.reads
      - sp.*.storage.lun.*.writes
    calculator: lun_response_time
  - name: queue_length
    paths:
      - sp.*.storage.lun.*.currentIOCount
      - sp.*.storage.lun.*.busyTime
      - sp.*.storage.lun.*.idleTime
    calculator: lun_queue_length
  - name: read_byte_rate
    paths:
      - sp.*.storage.lun.*.readBlocks
      - sp.*.storage.blockSize
    calculator: byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.storage.lun.*.writeBlocks
      - sp.*.storage.blockSize
    calculator: byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.storage.lun.*.readBlocks
      - sp.*.storage.lun.*.writeBlocks
      - sp.*.storage.blockSize
    calculator: total_byte_rate


UnityFileSystem:
  - name: read_iops
    paths: sp.*.storage.filesystem.*.reads
  - name: write_iops
    paths: sp.*.storage.filesystem.*.writes
  - name: read_mbps
    paths: sp.*.storage.filesystem.*.readBytes
    calculator: mb_ps_by_byte
  - name: write_mbps
    paths: sp.*.storage.filesystem.*.writeBytes
    calculator: mb_ps_by_byte


UnityStorageProcessor:
  - name: net_in_mbps
    paths: sp.*.net.basic.inBytes
    calculator: sp_mb_ps_by_byte
  - name: net_out_mbps
    paths: sp.*.net.basic.outBytes
    calculator: sp_mb_ps_by_byte
  - name: block_read_iops
    paths: sp.*.storage.summary.reads
    calculator: sp_delta_ps
  - name: block_write_iops
    paths: sp.*.storage.summary.writes
    calculator: sp_delta_ps
  - name: block_total_iops
    paths:
      - sp.*.storage.summary.reads
      - sp.*.storage.summary.writes
    calculator: sp_total_delta_ps
  - name: block_read_mbps
    paths: sp.*.storage.summary.readBlocks
    calculator: sp_mb_ps_by_block
  - name: block_write_mbps
    paths: sp.*.storage.summary.writeBlocks
    calculator: sp_mb_ps_by_block
  - name: cifs_read_iops
    paths: sp.*.cifs.global.basic.reads
    calculator: sp_delta_ps
  - name: cifs_write_iops
    paths: sp.*.cifs.global.basic.writes
    calculator: sp_delta_ps
  - name: cifs_read_mbps
    paths: sp.*.cifs.global.basic.readBytes
    calculator: sp_mb_ps_by_byte
  - name: cifs_write_mbps
    paths: sp.*.cifs.global.basic.writeBytes
    calculator: sp_mb_ps_by_byte
  - name: nfs_read_iops
    paths: sp.*.nfs.basic.reads
    calculator: sp_delta_ps
  - name: nfs_write_iops
    paths: sp.*.nfs.basic.writes
    calculator: sp_delta_ps
  - name: nfs_read_mbps
    paths: sp.*.nfs.basic.readBytes
    calculator: sp_mb_ps_by_byte
  - name: nfs_write_mbps
    paths: sp.*.nfs.basic.writeBytes
    calculator: sp_mb_ps_by_byte
  - name: utilization
    paths:
      - sp.*.cpu.summary.busyTicks
      - sp.*.cpu.summary.idleTicks
    calculator: sp_busy_idle_util
  - name: block_cache_read_hit_ratio
    paths:
      - sp.*.blockCache.global.summary.readHits
      - sp.*.blockCache.global.summary.readMisses
    calculator: sp_hit_ratio
  - name: block_cache_write_hit_ratio
    paths:
      - sp.*.blockCache.global.summary.writeHits
      - sp.*.blockCache.global.summary.writeMisses
    calculator: sp_hit_ratio
  - name: temperature
    paths: sp.*.platform.storageProcessorTemperature
    calculator: sp_fact
  - name: core_count
    paths: sp.*.physical.coreCount
    calculator: sp_fact
  - name: block_cache_dirty_size
    paths: sp.*.blockCache.global.summary.dirtyBytes
    calculator: sp_fact
  - name: read_byte_rate
    paths:
      - sp.*.storage.summary.readBlocks
      - sp.*.storage.blockSize
    calculator: sp_byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.storage.summary.writeBlocks
      - sp.*.storage.blockSize
    calculator: sp_byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.storage.summary.readBlocks
      - sp.*.storage.summary.writeBlocks
      - sp.*.storage.blockSize
    calculator: sp_total_byte_rate
  - name: fast_cache_read_hits
    paths: sp.*.fastCache.volume.*.readHits
    calculator: sp_sum_values
  - name: fast_cache_write_hits
    paths: sp.*.fastCache.volume.*.writeHits
    calculator: sp_sum_values
  - name: fast_cache_read_hit_rate
    paths:
      - sp.*.fastCache.volume.*.readHits
    calculator: sp_io_rate
  - name: fast_cache_write_hit_rate
    paths:
      - sp.*.fastCache.volume.*.writeHits
    calculator: sp_io_rate


UnityFcPort:
  - name: read_iops
    paths: sp.*.fibreChannel.fePort.*.reads
  - name: write_iops
    paths: sp.*.fibreChannel.fePort.*.writes
  - name: total_iops
    paths:
      - sp.*.fibreChannel.fePort.*.reads
      - sp.*.fibreChannel.fePort.*.writes
    calculator: total_delta_ps
  - name: read_byte_rate
    paths:
      - sp.*.fibreChannel.fePort.*.readBlocks
      - sp.*.fibreChannel.blockSize
    calculator: byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.fibreChannel.fePort.*.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.fibreChannel.fePort.*.readBlocks
      - sp.*.fibreChannel.fePort.*.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: total_byte_rate


UnityIscsiNode:
  - name: read_iops
    paths: sp.*.iscsi.fePort.*.reads
  - name: write_iops
    paths: sp.*.iscsi.fePort.*.writes
  - name: total_iops
    paths:
      - sp.*.iscsi.fePort.*.reads
      - sp.*.iscsi.fePort.*.writes
    calculator: total_delta_ps
  - name: read_byte_rate
    paths:
      - sp.*.iscsi.fePort.*.readBlocks
      - sp.*.fibreChannel.blockSize
    calculator: byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.iscsi.fePort.*.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.iscsi.fePort.*.readBlocks
      - sp.*.iscsi.fePort.*.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: total_byte_rate


UnitySystem:
  - name: read_iops
    paths: sp.*.storage.summary.reads
    calculator: system_delta_ps
  - name: write_iops
    paths: sp.*.storage.summary.writes
    calculator: system_delta_ps
  - name: total_iops
    paths:
      - sp.*.storage.summary.reads
      - sp.*.storage.summary.writes
    calculator: system_total_delta_ps
  - name: read_byte_rate
    paths:
      - sp.*.storage.summary.readBlocks
      - sp.*.fibreChannel.blockSize
    calculator: system_byte_rate
  - name: write_byte_rate
    paths:
      - sp.*.storage.summary.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: system_byte_rate
  - name: total_byte_rate
    paths:
      - sp.*.storage.summary.readBlocks
      - sp.*.storage.summary.writeBlocks
      - sp.*.fibreChannel.blockSize
    calculator: system_total_byte_rate
