# Generated by Django 3.1.1 on 2020-10-04 19:37
# Edited by reverend

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc

class Migration(migrations.Migration):

    dependencies = [
        ('lostplaces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher'
        ),
        migrations.DeleteModel(
            name='Expireable'
        )
    ]