# Generated by Django 3.1.1 on 2020-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostplaces', '0002_reomve_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('expires_when', models.DateTimeField()),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]