name: pyyaml_include-dev

dependencies:
  - python
  - pip
  - ipython
  - ipywidgets
  - nb_conda
  - pyyaml
  - toml
  - pytest
  - sphinx
  - recommonmark
  - coverage
  - setuptools_scm
  - setuptools_scm_git_archive
  - twine
  - autopep8
  - pylint
