# coding: utf-8

"""
    Aliro Q.Network

    This is an api for the Aliro Q.Network  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from aliro_aqn.configuration import Configuration


class SubmissionAqnOutput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'classical_channels': 'list[ClassicalChannel]',
        'name': 'str',
        'nodes': 'list[Node]',
        'quantum_connections': 'list[QuantumConnection]',
        'request': 'Request',
        'submission_aqn_type': 'str',
        'create_date': 'str'
    }

    attribute_map = {
        'classical_channels': 'classicalChannels',
        'name': 'name',
        'nodes': 'nodes',
        'quantum_connections': 'quantumConnections',
        'request': 'request',
        'submission_aqn_type': 'submissionAqnType',
        'create_date': 'createDate'
    }

    def __init__(self, classical_channels=None, name=None, nodes=None, quantum_connections=None, request=None, submission_aqn_type=None, create_date=None, local_vars_configuration=None):  # noqa: E501
        """SubmissionAqnOutput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._classical_channels = None
        self._name = None
        self._nodes = None
        self._quantum_connections = None
        self._request = None
        self._submission_aqn_type = None
        self._create_date = None
        self.discriminator = None

        if classical_channels is not None:
            self.classical_channels = classical_channels
        self.name = name
        self.nodes = nodes
        self.quantum_connections = quantum_connections
        if request is not None:
            self.request = request
        self.submission_aqn_type = submission_aqn_type
        self.create_date = create_date

    @property
    def classical_channels(self):
        """Gets the classical_channels of this SubmissionAqnOutput.  # noqa: E501


        :return: The classical_channels of this SubmissionAqnOutput.  # noqa: E501
        :rtype: list[ClassicalChannel]
        """
        return self._classical_channels

    @classical_channels.setter
    def classical_channels(self, classical_channels):
        """Sets the classical_channels of this SubmissionAqnOutput.


        :param classical_channels: The classical_channels of this SubmissionAqnOutput.  # noqa: E501
        :type: list[ClassicalChannel]
        """

        self._classical_channels = classical_channels

    @property
    def name(self):
        """Gets the name of this SubmissionAqnOutput.  # noqa: E501


        :return: The name of this SubmissionAqnOutput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SubmissionAqnOutput.


        :param name: The name of this SubmissionAqnOutput.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def nodes(self):
        """Gets the nodes of this SubmissionAqnOutput.  # noqa: E501


        :return: The nodes of this SubmissionAqnOutput.  # noqa: E501
        :rtype: list[Node]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this SubmissionAqnOutput.


        :param nodes: The nodes of this SubmissionAqnOutput.  # noqa: E501
        :type: list[Node]
        """
        if self.local_vars_configuration.client_side_validation and nodes is None:  # noqa: E501
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes

    @property
    def quantum_connections(self):
        """Gets the quantum_connections of this SubmissionAqnOutput.  # noqa: E501


        :return: The quantum_connections of this SubmissionAqnOutput.  # noqa: E501
        :rtype: list[QuantumConnection]
        """
        return self._quantum_connections

    @quantum_connections.setter
    def quantum_connections(self, quantum_connections):
        """Sets the quantum_connections of this SubmissionAqnOutput.


        :param quantum_connections: The quantum_connections of this SubmissionAqnOutput.  # noqa: E501
        :type: list[QuantumConnection]
        """
        if self.local_vars_configuration.client_side_validation and quantum_connections is None:  # noqa: E501
            raise ValueError("Invalid value for `quantum_connections`, must not be `None`")  # noqa: E501

        self._quantum_connections = quantum_connections

    @property
    def request(self):
        """Gets the request of this SubmissionAqnOutput.  # noqa: E501


        :return: The request of this SubmissionAqnOutput.  # noqa: E501
        :rtype: Request
        """
        return self._request

    @request.setter
    def request(self, request):
        """Sets the request of this SubmissionAqnOutput.


        :param request: The request of this SubmissionAqnOutput.  # noqa: E501
        :type: Request
        """

        self._request = request

    @property
    def submission_aqn_type(self):
        """Gets the submission_aqn_type of this SubmissionAqnOutput.  # noqa: E501


        :return: The submission_aqn_type of this SubmissionAqnOutput.  # noqa: E501
        :rtype: str
        """
        return self._submission_aqn_type

    @submission_aqn_type.setter
    def submission_aqn_type(self, submission_aqn_type):
        """Sets the submission_aqn_type of this SubmissionAqnOutput.


        :param submission_aqn_type: The submission_aqn_type of this SubmissionAqnOutput.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and submission_aqn_type is None:  # noqa: E501
            raise ValueError("Invalid value for `submission_aqn_type`, must not be `None`")  # noqa: E501

        self._submission_aqn_type = submission_aqn_type

    @property
    def create_date(self):
        """Gets the create_date of this SubmissionAqnOutput.  # noqa: E501


        :return: The create_date of this SubmissionAqnOutput.  # noqa: E501
        :rtype: str
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this SubmissionAqnOutput.


        :param create_date: The create_date of this SubmissionAqnOutput.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and create_date is None:  # noqa: E501
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubmissionAqnOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SubmissionAqnOutput):
            return True

        return self.to_dict() != other.to_dict()
