strict: true
site_name: tuxmake documentation
site_description: |
  Documentation for TuxMake, a command line tool and Python library utility
  that provides portable and repeatable Linux kernel builds across a variety of
  architectures, toolchains, kernel configurations, and make targets.
site_author: Tuxmake Team
site_dir: public
repo_url: https://gitlab.com/Linaro/tuxmake/
theme:
  name: material
  logo: tuxmake.svg
  favicon: tuxmake_icon.svg
markdown_extensions:
  - mkautodoc
extra_css:
  - mkautodoc.css
  - extra.css

nav:
- Introduction:
  - Getting Started: index.md
  - Command line reference: cli.md
  - Python API: python.md
- Reference Documentation:
  - Targets: targets.md
  - Target architectures: architectures.md
  - Toolchains: toolchains.md
  - Kernel Configuration: kconfig.md
  - Compiler wrappers: wrappers.md
  - Runtimes: runtimes.md
  - Metadata: metadata.md
- TuxMake community:
  - Code of Conduct: code-of-conduct.md
  - Contributing: contributing.md
  - Downstream packaging: packaging.md
  - License: license.md
