[tool.poetry]
name = "rearq"
version = "0.1.4"
description = "Rewrite arq and make improvement."
authors = ["long2ice <long2ice@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/long2ice/rearq.git"
repository = "https://github.com/long2ice/rearq.git"
documentation = "https://github.com/long2ice/rearq/blob/master/README.md"
keywords = ["asyncio", "task", "arq", "queue", "distributed"]
packages = [
    { include = "rearq" }
]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "*"
click = "*"
aioredis = "*"
crontab = "*"

[tool.poetry.dev-dependencies]
taskipy = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest = "*"
pytest-xdist = "*"
bandit = "*"
pytest-asyncio = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
rearq = "rearq.cli:main"
