[tool.poetry]
name = "splink"
version = "0.4.2"
description = "Implementation in Apache Spark of the EM algorithm to estimate parameters of Fellegi-Sunter's canonical model of record linkage."
authors = ["Robin Linacre <robinlinacre@hotmail.com>", "Sam Lindsay", "Theodore Manassis"]
license = "MIT"
homepage = "https://github.com/moj-analytical-services/splink"
repository = "https://github.com/moj-analytical-services/splink"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
jsonschema = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pandas = "^0.25.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
