active_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
  - verb: fill
    name: email
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.0312
      - mode: name
        value: signup-email
        index: 0
        score: 0.0312
      - mode: name
        value: email
        index: 0
        score: 0.0312
      - mode: id
        value: signup-email
        index: 0
        score: 0.0312
      - mode: id
        value: email
        index: 0
        score: 0.0312
      - mode: css
        value: '[aria-label="Email"]'
        index: 0
        score: 0.0312
