[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
skip_string_normalization = true

[tool.flit.metadata]
author = "Yura52"
author-email = "strausmg@gmail.com"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dist-name = "libzero"
home-page = "https://github.com/Yura52/zero"
keywords = "artificial intelligence, deep learning, library, python, pytorch, torch"
module = "zero"
requires = [
    "numpy >=1.17,<2",
    "pynvml >= 8.0,<9",
    "torch >= 1.4,<2",
    "tqdm >= 4.0,<5"
]
requires-python = ">=3.6"
