BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXX
XXXXXXXXXXXXXXX gettext(u'link') XXXXX
    XXXX gettext(u'amount debited') XXXXX
    XXXX gettext(u'amount refund') XXXXX
    XXXX gettext(u'customer balance') XXXXX
    XXXX gettext(u'supplier balance') XXXXX
    XXXX gettext(u'operation type') XXXXX
    XXXX gettext(u'external description') XXXXX
    XXXX gettext(u'internal description') XXXXX
XXXXX
BBB BBBBBB BB BBBBBBBBBBB
XXXX
    XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
XXXXX
BBBBBB
XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XXX XXXXXX XXXXXX
BBBBBBBB
