BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'company listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXXXXXX gettext(u'name') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'created') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'modified') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'address') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'contact name') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'contact phone') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'customer balance') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'supplier balance') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'created') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'modified') XXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'edit company') XXXX

BBBBBBBB
