BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'balance history') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXXXXXX gettext(u'amount debited') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'amount refund') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'customer balance') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'supplier balance') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'operation type') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'external description') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'internal description') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'created') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'modified') XXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'edit') XXXX

BBBBBBBB
