BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'company listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXX
XXXXXXXXXXXXXXX gettext(u'link') XXXXX
    XXXX gettext(u'name') XXXXX
    XXXX gettext(u'contact name') XXXXX
    XXXX gettext(u'contact phone') XXXXX
    XXXX gettext(u'customer balance') XXXXX
    XXXX gettext(u'supplier balance') XXXXX
XXXXX
BBB BBBBBB BB BBBBBBBBBBB
XXXX
    XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
XXXXX
BBBBBB
XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'create new company') XXXX
BBBBBBBB
