BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'customer listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXX
XXXXXXXXXXXXXXX gettext(u'link') XXXXX
    XXXX gettext(u'credit_limit') XXXXX
    XXXX gettext(u'max_calls') XXXXX
    XXXX gettext(u'calls_per_second') XXXXX
    XXXX gettext(u'customer_enabled') XXXXX
XXXXX
BBB BBBBBB BB BBBBBBBBBBB
XXXX
    XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
    XXXXXXXXX
XXXXX
BBBBBB
XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'create new customer') XXXX
BBBBBBBB
