BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'customer listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXXXXXX gettext(u'account number') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'credit limit') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'low credit alert') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'max simultaneous calls') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'calls per second limit') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'enabled') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'created') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'modified') XXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'edit customer') XXXX

BBBBBBBB
