BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'provider listing') XXXXXXXX
XXXXX XXXXXXXXXXXXXX
BBBBBBBBBB
FFFFFF
XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'submit') XXXXXXXXX
XXXXXXX
BBBBBBBB
