BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'provider listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXXXXXX gettext(u'enabled') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'created') XXXXXXXXXXXXXXXXXXX
XXXXXXXX gettext(u'modified') XXXXXXXXXXXXXXXXXXX
XXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'edit provider') XXXX

BBBBBBBB
