BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBBB BBBBBBB
XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'provider listing') XXXXXXXX
XXXXXX XXXXXXXXXXXXXX
XXXX
XXXXXXXXXXXXXXX gettext(u'link') XXXXX
    XXXX gettext(u'enabled') XXXXX
XXXXX
BBB BBBBBB BB BBBBBBBBBBB
XXXX
    XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXX
XXXXX
BBBBBB
XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'create new provider') XXXX
BBBBBBBB
