
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-26T22:23:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f4d7c4f7219444fc5674404b5488bb5d0e81535",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
