
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-25T18:19:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a9d1e361b77adaeceb5871146d3852788af5cdc",
 "version": "2.4.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
