[tool.poetry]
name = "crowbar-reference-compiler"
version = "0.0.6"
description = "the reference compiler for the Crowbar programming language"
authors = ["Melody Horn <melody@boringcactus.com>"]
license = "BlueOak-1.0.0"
readme = "README.md"
repository = "https://git.sr.ht/~boringcactus/crowbar-reference-compiler"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Other",
    "Topic :: Software Development :: Compilers",
]

[tool.poetry.scripts]
crowbarc-reference = "crowbar_reference_compiler:main"

[tool.poetry.dependencies]
python = "^3.7"
parsimonious = "^0.8.1"
regex = "^2020.10.11"

[tool.poetry.dev-dependencies]
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
