
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-20T19:39:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e6d059d80cc2f553a894fd1f378e75bfafc34c1",
 "version": "0.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
