[tool.poetry]
name = "simdak"
version = "1.0.0"
description = "Importer-exporter data Simdak Kemdikbud"
authors = ["hexatester <habibrohman@gmail.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/dapodix/simdak"
repository = "https://github.com/dapodix/simdak"
include = [
    "LICENSE",
    "README.md",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.0"
bs4 = "^0.0.1"
openpyxl = "^3.0.5"
click = "^7.1.2"
fuzzywuzzy = "^0.18.0"
python-Levenshtein = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
mypy = "^0.790"
click = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
