# pylint: skip-file
import os

KMS_REGION = os.getenv('TEST_GOOGLE_KMS_REGION')
KMS_PROJECT = os.getenv('TEST_GOOGLE_KMS_PROJECT')
KMS_KEYRING = os.getenv('TEST_GOOGLE_KMS_KEYRING')
KMS_SIGNING_KEY = os.getenv('TEST_GOOGLE_KMS_SIGNING_KEY')
KMS_SIGNING_KEY_VERSION = os.getenv('TEST_GOOGLE_KMS_SIGNING_KEY_VERSION')
KMS_ENCRYPTION_KEY = os.getenv('TEST_GOOGLE_KMS_ENCRYPTION_KEY')

KMS_KEYRING_OK = bool(KMS_REGION and KMS_PROJECT and KMS_KEYRING)
KMS_SIGNING_OK = bool(KMS_KEYRING and KMS_SIGNING_KEY and KMS_SIGNING_KEY_VERSION)
KMS_ENCRYPTION_OK = bool(KMS_KEYRING and KMS_ENCRYPTION_KEY)
