apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls
spec:
  template:
    spec:
      serviceAccountName: mtls
      initContainers:
        - name: mtls-init-user-keys
          image: kiwigrid/k8s-sidecar:0.1.178
          env:
            - name: LABEL
              value: mtls_user_key
            - name: METHOD
              value: LIST
            - name: FOLDER
              value: /tmp/user_keys
          volumeMounts:
            - name: sc-user-keys-volume
              mountPath: /tmp/user_keys
        - name: mtls-init-admin-keys
          image: kiwigrid/k8s-sidecar:0.1.178
          env:
            - name: LABEL
              value: mtls_admin_key
            - name: METHOD
              value: LIST
            - name: FOLDER
              value: /tmp/admin_keys
          volumeMounts:
            - name: sc-admin-keys-volume
              mountPath: /tmp/admin_keys
        - name: mtls-seed-trust-stores
          image: drgrove/mtls-server
          env:
            - name: USER_GNUPGHOME
              value: /home/mtls/secrets/gnupg/
            - name: USER_SEED_FOLDER
              value: /tmp/seeds/user/
            - name: ADMIN_GNUPGHOME
              value: /home/mtls/secrets/admin_gnupg/
            - name: ADMIN_SEED_FOLDER
              value: /tmp/seeds/admin/
          command:
            - /tmp/seed.sh
          volumeMounts:
            - name: sc-user-keys-volume
              mountPath: /tmp/seeds/user
            - name: sc-admin-keys-volume
              mountPath: /tmp/seeds/admin
            - name: persistence
              mountPath: /home/mtls/secrets/gnupg/
              subPath: "gnupg"
              readOnly: false
            - name: persistence
              mountPath: /home/mtls/secrets/admin_gnupg/
              subPath: "admin_gnupg"
              readOnly: false
            - name: mtls-seed-script
              mountPath: /tmp/seed.sh
              subPath: "seed.sh"
              readOnly: true
      containers:
        - name: mtls
          volumeMounts:
            - name: sc-user-keys-volume
              mountPath: /tmp/seeds/user
            - name: sc-admin-keys-volume
              mountPath: /tmp/seeds/admin
      volumes:
        - name: sc-user-keys-volume
          emptyDir: {}
        - name: sc-admin-keys-volume
          emptyDir: {}
        - name: mtls-seed-script
          configMap:
            name: mtls-seed-script
            defaultMode: 0777
