apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
  - mtls-role.yml
  - mtls-serviceaccount.yml
patches:
  - add-init-containers.patch.yml
  - disable-seed-on-init.patch.yml
configMapGenerator:
  - name: mtls-seed-script
    files:
      - ./files/seed.sh
images:
  - name: kiwigrid/k8s-sidecar
    newName: drgrove/k8s-sidecar
    digest: sha256:8799b42ad45245b63a85e0e2190914da8d32472f3cd98f057cc332ca32be98cc
