apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtls-rolebinding
roleRef:
  kind: Role
  name: mtls-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: mtls
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtls-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
