
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T14:25:13+1100",
 "dirty": true,
 "error": null,
 "full-revisionid": "4209038f154968e7bc573c4a571c0381933d1233",
 "version": "0+untagged.105.g4209038.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
