version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  labels:
  - DEPENDABOT
  commit-message:
    prefix: "[DEPENDABOT]"
