[tool.poetry]
name = "django_gmzoom_tools"
version = "0.1.2"
description = "Slotmarks.com - online casino guide"
authors = ["slotmarks <info@slotmarks.com>"]
homepage = "https://slotmarks.com/en/"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
