
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-26T08:26:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc71add94b3e714518e8b328b5b43425ad0244e1",
 "version": "2.0.46.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
