
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-24T20:16:16+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "df287cba7caed1d96cb9d7c422d57c4d7342a3cc",
 "version": "2.0.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
