[tool.poetry]
name = "tinderdata"
version = "0.4"
description = "A silly utility to explore your Tinder data."
authors = ["Felix Soubelet <felix.soubelet@liverpool.ac.uk>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/fsoubelet/Tinder_Data"

keywords = ["Utility", "Visualisation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0"
matplotlib = "^3.2"
seaborn = "^0.10"
loguru = "^0.4"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
typer-cli = "^0.0.11"

[tool.poetry.scripts]
tinderdata = "tinderdata.__main__:app"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
