# Generated by Django 2.1.11 on 2019-09-02 11:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_privacy_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingitem',
            name='category',
            field=models.CharField(choices=[('ESSENTIAL', 'Essential'), ('STATISTICS', 'Statistics'), ('MARKETING', 'Marketing')], default='ESSENTIAL', max_length=1024),
        ),
        migrations.AlterField(
            model_name='trackingitemtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='django_privacy_mgmt.TrackingItem'),
        ),
    ]
