
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T22:19:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2c7d5706ea44e35ab9f698ba1b49abef1960f86",
 "version": "0.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
