name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ '**.py' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.py' ]

jobs:
  precommit_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install black isort flake8 flake8-bugbear mypy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --check .
      - name: Run flake8
        run: flake8 --statistics .
      - name: Run mypy
        run: mypy .

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO: Add 3.9 after https://github.com/equinor/segyio/pull/486 is released
        python-version: ['3.6', '3.7', '3.8']
        exclude:
        - os: windows-latest
          python-version: '3.6'
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Numpy < 1.20
        if: ${{ matrix.python-version < '3.7' }}
        run: pip install 'numpy<1.20'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TileDB-Segy
        run: python setup.py install
      - name: Test with coverage
        run: |
          python setup.py test --addopts "
            --cov=tiledb
            --cov-report=term-missing
            --cov-report=html:coverage
            --cov-report=xml:coverage/coverage.xml
          "
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
