[tool.poetry]
name = "ml-idm"
version = "0.0.1"
description = ""
authors = ["Ilya Tyutin <emmarrgghh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.4"
streamlit = "^0.71.0"
joblib = "^0.17.0"
pyyaml = "^5.3.1"
pydantic = "^1.7.2"
matplotlib = "^3.3.3"
pre-commit = "^2.9.2"
mypy = "^0.790"
black = "19.10b0"
flake8 = "^3.8.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
