
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-18T15:25:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8714604ac0d1361e5651fbf5c4f1f4b24bb6fe7e",
 "version": "v0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
