active_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
  - verb: click
    name: sign_up
    locators:
      - mode: text
        value: Sign Up
        index: 0
        score: 0.625
