
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T12:32:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c1af1592ce226a3c2481ad64a394ef618f626b2",
 "version": "v2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
