version: '3.7'

services:
  fake_mesh:
    image: ${DOCKER_REGISTRY-}fake_mesh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8829:8829"
    volumes:
      -  ./fake_mesh_dir:/tmp/fake_mesh_dir
