# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 13:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eox_audit_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('audit_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eox_audit_model.AuditModel')),
            ],
        ),
    ]
