[tool.poetry]
name = "peppers"
version = "0.1.1"
description = "peppers for soup? Pyppers for Python!"
authors = ["innerNULL"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple/"
default = true 
