
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T14:16:49-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7643255ac3d6f4ed1d6086cc2ad37c281659ea95",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
