# SPDX-License-Identifier: MIT
# Copyright (c) 2020  GitHub, Inc. and contributors
# see https://github.com/actions/starter-workflows/
#
# vim: set filetype=yaml ts=2 sts=2 sw=2 expandtab
#
name: pypi
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy PyPI
    runs-on: ubuntu-latest
    env:
      FLIT_USERNAME: '__token__'
      FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install flit
          python -m flit publish

