
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T17:16:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5bf7b32042d832b1e46bad4ef7784348793ec8b",
 "version": "0.7.80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
