
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-17T21:18:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e505b81e78efbf9442da3b87762e05e28c4c50ed",
 "version": "0.1.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
