os: linux
dist: focal
language: python

jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9"
  - python: "3.8"
    arch: arm64-graviton2
    virt: vm
    group: edge
  - python: "3.8"
    arch: ppc64le
  - python: "3.8"
    arch: s390x
  - python: "3.8"
    env: LINTER=1

services:
  - docker

notifications:
  email: false

before_install:
  - pip install --upgrade pip setuptools

install:
  - pip install -r test-requirements.txt
  - pip install tox codecov
  - pip install -e .
  # pull manylinux images that will be used, this helps passing tests which would otherwise timeout.
  - python -c $'from tests.integration.test_manylinux import MANYLINUX_IMAGES\nfor image in MANYLINUX_IMAGES.values():\n    print(image)' | xargs -L 1 docker pull

script:
  - tests/travis.sh

cache:
  directories:
    - $HOME/.cache/auditwheel_tests
