[tool.poetry]
name = "checkbox-api"
version = "0.1.16"
description = "checkbox.in.ua Transactional Processing API Client"
authors = ["Oleksandr Onufriichuk <oleksandr.onufriichuk@itvaan.com.ua>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.13.3"
PyJWT = "^1.7.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^5.2.2"
flake8 = "^3.8.3"
autoflake = "^1.3.1"
ipython = "^7.17.0"

[tool.black]
line-length = 99
target-version = ['py38']
exclude = '''
(
    \.eggs
  | \.git
  | build
  | dist
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99
known_third_party = ["httpx", "jwt", "httpcore"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
