
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-18T08:26:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d344b506b5c185f33dec9a576415f9407a9f6933",
 "version": "v0.2.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
