[tool.poetry]
name = "switchcraft"
version = "0.14.0"
description = "Client wrappers and helpful utilities to solve common coding challenges in AWS"
authors = ["WWPS ProServe"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
readme = "README.md"
keywords = ["switchcraft", "aws", "lambda"]
license = "MIT-0"

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.16.3"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.isort]
profile = "hug"
src_paths = ["switchcraft", "test"]
line_length = 80
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true

known_first_party = "switchcraft"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
