# We will add noise to our signals. Keep in mind that this will cause some events
# to trigger on noise. To study the number of fortuitious triggers, setting
# zerosignal: True will perform a simulation with noise only.
noise: True

# This controls the electric field model that is used
signal:
  # We recommend the Alvarez2009 model for the simulation of effective volumes
  # For reconstruction purposes, where accuracy is most needed, we recommend the
  # ARZ2020 model.
  model: Alvarez2009
  zerosignal: False
# There is a variety of ice models we can choose from.
propagation:
  # For the refractive index, there are: greenland_simple, mooresbay_simple,
  # southpole_2015, southpole_simple, and ARAsim_southpole. See utilities.medium
  # to know their refractive index profile.
  ice_model: greenland_simple
  # We have three available attenuation models: GL1 for Greenland, MB1 for
  # Moore's Bay, and SP1 for South Pole.
  attenuation_model: GL1

# With the speedum parameters, we can ignore the events that do not pass certain
# geometric or amplitude cuts. Their triggers will not be calculated and they
# will be counted as a non-triggering event.
speedup:
  # If the weight of a neutrino event is less than minimum_weight_cut, it will be ignored.
  minimum_weight_cut: 1.e-5
  # min_efield_amplitude is the minimum signal amplitude of the efield as a factor of the noise RMS.
  # If the value is smaller, no detector simulation is performed. As the vector effecive length of
  # antennas is typically less than 1, this cut does not introduce any bias as long as the value is
  # smaller than the trigger threshold.
  min_efield_amplitude: 2

trigger:
  noise_temperature: 300  # in Kelvin
