[tool.poetry]
name = "dh-potluck"
version = "0.6.2"
authors = []
description = ""

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.0"
webargs = "^5.5.2"
marshmallow = "^2.19"
sqlalchemy = "^1.3"
ddtrace = ">=0.25.0"
boltons = "^19.1"
Werkzeug = ">=0.15.0"
requests = "^2.22"
flask-limiter = "^1.2.1"
json-log-formatter = "^0.3.0"
flask_sqlalchemy = "^2.4.4"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^4.4"
flake8-quotes = "^1.0"
flake8-import-order = "^0.18.1"
vcrpy = "^2.0"
freezegun = "^0.3.15"
redis = "^3.4.1"
