[tool.poetry]
name = "spectrogram_to_audio"
version = "0.0.5"
description = ""
authors = ["carl2g <degentilecarl@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6, <3.9"
tensorflow = "^2.3.1"
tensorflow-io = "^0.16.0"
tensorflow-datasets = "^4.1.0"
tensorflow-addons = "^0.11.2"
dynaconf = "^3.1.2"

[tool.poetry.dev-dependencies]
coverage = "^5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
