
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-22T21:34:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1cbf363769d069656ac20e360a8f3775db13671e",
 "version": "v2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
