INPUT_IMAGES_DIR: '/data/dataset/trafficsign_13classes/test/images/'
INPUT_LABELS_DIR: '/data/dataset/trafficsign_13classes/test/labels_only_13classes/'
OUTPUT_DIR: '/data/dataset/json2coco/'
CLASS_ID:
    "00": 1
    "01": 2 
    "02": 3
    "03": 4
    "04": 5
    "05": 6
    "06": 7
    "07": 8
    "08": 9
    "09": 10
    "0A": 11
    "0B": 12
    "0C": 13