# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainView.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 494)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.outline = QtWidgets.QTreeView(self.centralwidget)
        self.outline.setObjectName("outline")
        self.outline.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.outline)
        self.widgetStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.widgetStack.setObjectName("widgetStack")
        self.addSet = QtWidgets.QWidget()
        self.addSet.setObjectName("addSet")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.addSet)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.addSet)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.newSetName = QtWidgets.QLineEdit(self.addSet)
        self.newSetName.setObjectName("newSetName")
        self.horizontalLayout_3.addWidget(self.newSetName)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.addSet)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.layoutChooserAddSet = QtWidgets.QComboBox(self.addSet)
        self.layoutChooserAddSet.setObjectName("layoutChooserAddSet")
        self.horizontalLayout.addWidget(self.layoutChooserAddSet)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.setDefaultLayout = QtWidgets.QCheckBox(self.addSet)
        self.setDefaultLayout.setObjectName("setDefaultLayout")
        self.verticalLayout_3.addWidget(self.setDefaultLayout)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.createSetButton = QtWidgets.QPushButton(self.addSet)
        self.createSetButton.setObjectName("createSetButton")
        self.verticalLayout_11.addWidget(self.createSetButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.previewAddSet = LayoutPreview(self.addSet)
        self.previewAddSet.setMinimumSize(QtCore.QSize(100, 0))
        self.previewAddSet.setObjectName("previewAddSet")
        self.horizontalLayout_6.addWidget(self.previewAddSet)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.widgetStack.addWidget(self.addSet)
        self.editSet = QtWidgets.QWidget()
        self.editSet.setObjectName("editSet")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.editSet)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.previewEditSet = LayoutPreview(self.editSet)
        self.previewEditSet.setObjectName("previewEditSet")
        self.verticalLayout_20.addWidget(self.previewEditSet)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.layoutChooserEditSet = QtWidgets.QComboBox(self.editSet)
        self.layoutChooserEditSet.setObjectName("layoutChooserEditSet")
        self.horizontalLayout_7.addWidget(self.layoutChooserEditSet)
        self.setLayoutButton = QtWidgets.QPushButton(self.editSet)
        self.setLayoutButton.setObjectName("setLayoutButton")
        self.horizontalLayout_7.addWidget(self.setLayoutButton)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.removeSetButton = QtWidgets.QPushButton(self.editSet)
        self.removeSetButton.setObjectName("removeSetButton")
        self.horizontalLayout_20.addWidget(self.removeSetButton)
        self.addAudioButton = QtWidgets.QPushButton(self.editSet)
        self.addAudioButton.setObjectName("addAudioButton")
        self.horizontalLayout_20.addWidget(self.addAudioButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_20)
        self.verticalLayout_20.setStretch(0, 5)
        self.verticalLayout_20.setStretch(1, 1)
        self.verticalLayout_20.setStretch(2, 1)
        self.widgetStack.addWidget(self.editSet)
        self.editContainer = QtWidgets.QWidget()
        self.editContainer.setObjectName("editContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.editContainer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.containerTabs = QtWidgets.QTabWidget(self.editContainer)
        self.containerTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.containerTabs.setObjectName("containerTabs")
        self.fileDialog = QtWidgets.QWidget()
        self.fileDialog.setObjectName("fileDialog")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fileDialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.containerName = QtWidgets.QLabel(self.fileDialog)
        self.containerName.setObjectName("containerName")
        self.verticalLayout.addWidget(self.containerName)
        self.containerStatus = QtWidgets.QLabel(self.fileDialog)
        self.containerStatus.setObjectName("containerStatus")
        self.verticalLayout.addWidget(self.containerStatus)
        self.useOriginalFiles = QtWidgets.QCheckBox(self.fileDialog)
        self.useOriginalFiles.setObjectName("useOriginalFiles")
        self.verticalLayout.addWidget(self.useOriginalFiles)
        self.addFileButton = QtWidgets.QPushButton(self.fileDialog)
        self.addFileButton.setObjectName("addFileButton")
        self.verticalLayout.addWidget(self.addFileButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.previewContainer = LayoutPreview(self.fileDialog)
        self.previewContainer.setObjectName("previewContainer")
        self.horizontalLayout_4.addWidget(self.previewContainer)
        self.containerTabs.addTab(self.fileDialog, "")
        self.syncDialog = QtWidgets.QWidget()
        self.syncDialog.setObjectName("syncDialog")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.syncDialog)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.changeSyncButton = QtWidgets.QPushButton(self.syncDialog)
        self.changeSyncButton.setObjectName("changeSyncButton")
        self.verticalLayout_8.addWidget(self.changeSyncButton)
        self.verifyButton = QtWidgets.QPushButton(self.syncDialog)
        self.verifyButton.setObjectName("verifyButton")
        self.verticalLayout_8.addWidget(self.verifyButton)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.event1pic = QtWidgets.QLabel(self.syncDialog)
        self.event1pic.setObjectName("event1pic")
        self.verticalLayout_7.addWidget(self.event1pic)
        self.event1text = QtWidgets.QLabel(self.syncDialog)
        self.event1text.setObjectName("event1text")
        self.verticalLayout_7.addWidget(self.event1text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.event2pic = QtWidgets.QLabel(self.syncDialog)
        self.event2pic.setObjectName("event2pic")
        self.verticalLayout_9.addWidget(self.event2pic)
        self.event2text = QtWidgets.QLabel(self.syncDialog)
        self.event2text.setObjectName("event2text")
        self.verticalLayout_9.addWidget(self.event2text)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.syncDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.timestampHintEdit = QtWidgets.QLineEdit(self.syncDialog)
        self.timestampHintEdit.setObjectName("timestampHintEdit")
        self.horizontalLayout_10.addWidget(self.timestampHintEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.containerTabs.addTab(self.syncDialog, "")
        self.cropDialog = QtWidgets.QWidget()
        self.cropDialog.setObjectName("cropDialog")
        self.containerTabs.addTab(self.cropDialog, "")
        self.horizontalLayout_5.addWidget(self.containerTabs)
        self.widgetStack.addWidget(self.editContainer)
        self.editAudio = QtWidgets.QWidget()
        self.editAudio.setObjectName("editAudio")
        self.playSampleButton = QtWidgets.QPushButton(self.editAudio)
        self.playSampleButton.setGeometry(QtCore.QRect(160, 10, 101, 27))
        self.playSampleButton.setObjectName("playSampleButton")
        self.changeAudioButton = QtWidgets.QPushButton(self.editAudio)
        self.changeAudioButton.setGeometry(QtCore.QRect(160, 50, 101, 27))
        self.changeAudioButton.setObjectName("changeAudioButton")
        self.verifyAudioButton = QtWidgets.QPushButton(self.editAudio)
        self.verifyAudioButton.setGeometry(QtCore.QRect(160, 120, 101, 27))
        self.verifyAudioButton.setObjectName("verifyAudioButton")
        self.changeAudioEdit = QtWidgets.QLineEdit(self.editAudio)
        self.changeAudioEdit.setGeometry(QtCore.QRect(260, 50, 113, 27))
        self.changeAudioEdit.setObjectName("changeAudioEdit")
        self.layoutWidget = QtWidgets.QWidget(self.editAudio)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 141, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.audioLabel = QtWidgets.QLabel(self.layoutWidget)
        self.audioLabel.setObjectName("audioLabel")
        self.verticalLayout_10.addWidget(self.audioLabel)
        self.audioSyncLabel = QtWidgets.QLabel(self.layoutWidget)
        self.audioSyncLabel.setObjectName("audioSyncLabel")
        self.verticalLayout_10.addWidget(self.audioSyncLabel)
        self.removeAudio = QtWidgets.QPushButton(self.layoutWidget)
        self.removeAudio.setObjectName("removeAudio")
        self.verticalLayout_10.addWidget(self.removeAudio)
        self.forceExactTime = QtWidgets.QCheckBox(self.editAudio)
        self.forceExactTime.setGeometry(QtCore.QRect(160, 80, 211, 22))
        self.forceExactTime.setObjectName("forceExactTime")
        self.widgetStack.addWidget(self.editAudio)
        self.editFile = QtWidgets.QWidget()
        self.editFile.setObjectName("editFile")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.editFile)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filenameLabel = QtWidgets.QLabel(self.editFile)
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout_5.addWidget(self.filenameLabel)
        self.label_2 = QtWidgets.QLabel(self.editFile)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.moveUp = QtWidgets.QPushButton(self.editFile)
        self.moveUp.setObjectName("moveUp")
        self.verticalLayout_6.addWidget(self.moveUp)
        self.moveDown = QtWidgets.QPushButton(self.editFile)
        self.moveDown.setObjectName("moveDown")
        self.verticalLayout_6.addWidget(self.moveDown)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.removeFile = QtWidgets.QPushButton(self.editFile)
        self.removeFile.setObjectName("removeFile")
        self.verticalLayout_6.addWidget(self.removeFile)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.widgetStack.addWidget(self.editFile)
        self.verticalLayout_2.addWidget(self.widgetStack)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prepareButton = QtWidgets.QPushButton(self.centralwidget)
        self.prepareButton.setObjectName("prepareButton")
        self.horizontalLayout_2.addWidget(self.prepareButton)
        self.syncButton = QtWidgets.QPushButton(self.centralwidget)
        self.syncButton.setObjectName("syncButton")
        self.horizontalLayout_2.addWidget(self.syncButton)
        self.mergeButton = QtWidgets.QPushButton(self.centralwidget)
        self.mergeButton.setObjectName("mergeButton")
        self.horizontalLayout_2.addWidget(self.mergeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.widgetStack.setCurrentIndex(2)
        self.containerTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "c5sync"))
        self.label_4.setText(_translate("MainWindow", "Name:"))
        self.label_5.setText(_translate("MainWindow", "Layout:"))
        self.setDefaultLayout.setText(_translate("MainWindow", "set default"))
        self.createSetButton.setText(_translate("MainWindow", "Create Set"))
        self.setLayoutButton.setText(_translate("MainWindow", "Apply"))
        self.removeSetButton.setText(_translate("MainWindow", "remove Set"))
        self.addAudioButton.setText(_translate("MainWindow", "add Audio"))
        self.containerName.setText(_translate("MainWindow", "Name: ContainerName"))
        self.containerStatus.setText(_translate("MainWindow", "Status: ContainerStatus"))
        self.useOriginalFiles.setText(_translate("MainWindow", "Use Orignal Files"))
        self.addFileButton.setText(_translate("MainWindow", "Add File"))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.fileDialog), _translate("MainWindow", "Files"))
        self.changeSyncButton.setText(_translate("MainWindow", "change events"))
        self.verifyButton.setText(_translate("MainWindow", "verify events"))
        self.event1pic.setText(_translate("MainWindow", "e1pic"))
        self.event1text.setText(_translate("MainWindow", "e1text"))
        self.event2pic.setText(_translate("MainWindow", "e2pic"))
        self.event2text.setText(_translate("MainWindow", "e2text"))
        self.label.setText(_translate("MainWindow", "Event 1 Timestamp"))
        self.timestampHintEdit.setInputMask(_translate("MainWindow", "9999999999999"))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.syncDialog), _translate("MainWindow", "Sync"))
        self.containerTabs.setTabText(self.containerTabs.indexOf(self.cropDialog), _translate("MainWindow", "Cropping"))
        self.playSampleButton.setText(_translate("MainWindow", "play sample"))
        self.changeAudioButton.setText(_translate("MainWindow", "change sync"))
        self.verifyAudioButton.setText(_translate("MainWindow", "verify sync"))
        self.audioLabel.setText(_translate("MainWindow", "audioLabel"))
        self.audioSyncLabel.setText(_translate("MainWindow", "audioSyncLabel"))
        self.removeAudio.setText(_translate("MainWindow", "remove"))
        self.forceExactTime.setText(_translate("MainWindow", "force exact time"))
        self.filenameLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.moveUp.setText(_translate("MainWindow", "Move Up"))
        self.moveDown.setText(_translate("MainWindow", "Move Down"))
        self.removeFile.setText(_translate("MainWindow", "Remove File"))
        self.prepareButton.setText(_translate("MainWindow", "Prepare Container"))
        self.syncButton.setText(_translate("MainWindow", "Detect Sync"))
        self.mergeButton.setText(_translate("MainWindow", "Create Views"))

from .layout_preview import LayoutPreview
