# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoWidget.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_videoWidget(object):
    def setupUi(self, videoWidget):
        videoWidget.setObjectName("videoWidget")
        videoWidget.resize(446, 488)
        videoWidget.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(videoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoLayer = CVVideoWidget(videoWidget)
        self.videoLayer.setObjectName("videoLayer")
        self.verticalLayout.addWidget(self.videoLayer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(videoWidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(videoWidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gotoButton = QtWidgets.QPushButton(videoWidget)
        self.gotoButton.setObjectName("gotoButton")
        self.horizontalLayout.addWidget(self.gotoButton)
        self.frameInput = QtWidgets.QLineEdit(videoWidget)
        self.frameInput.setObjectName("frameInput")
        self.horizontalLayout.addWidget(self.frameInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setE1Button = QtWidgets.QPushButton(videoWidget)
        self.setE1Button.setObjectName("setE1Button")
        self.horizontalLayout_2.addWidget(self.setE1Button)
        self.gotoE1Button = QtWidgets.QPushButton(videoWidget)
        self.gotoE1Button.setObjectName("gotoE1Button")
        self.horizontalLayout_2.addWidget(self.gotoE1Button)
        self.setE2Button = QtWidgets.QPushButton(videoWidget)
        self.setE2Button.setObjectName("setE2Button")
        self.horizontalLayout_2.addWidget(self.setE2Button)
        self.gotoE2Button = QtWidgets.QPushButton(videoWidget)
        self.gotoE2Button.setObjectName("gotoE2Button")
        self.horizontalLayout_2.addWidget(self.gotoE2Button)
        self.currentFrameLabel = QtWidgets.QLabel(videoWidget)
        self.currentFrameLabel.setObjectName("currentFrameLabel")
        self.horizontalLayout_2.addWidget(self.currentFrameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.event1Label = QtWidgets.QLabel(videoWidget)
        self.event1Label.setObjectName("event1Label")
        self.horizontalLayout_3.addWidget(self.event1Label)
        self.event2Label = QtWidgets.QLabel(videoWidget)
        self.event2Label.setObjectName("event2Label")
        self.horizontalLayout_3.addWidget(self.event2Label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.e1List = QtWidgets.QListWidget(videoWidget)
        self.e1List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.e1List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.e1List.setIconSize(QtCore.QSize(300, 200))
        self.e1List.setFlow(QtWidgets.QListView.LeftToRight)
        self.e1List.setViewMode(QtWidgets.QListView.ListMode)
        self.e1List.setObjectName("e1List")
        self.horizontalLayout_4.addWidget(self.e1List)
        self.e2List = QtWidgets.QListWidget(videoWidget)
        self.e2List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.e2List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.e2List.setIconSize(QtCore.QSize(300, 200))
        self.e2List.setFlow(QtWidgets.QListView.LeftToRight)
        self.e2List.setViewMode(QtWidgets.QListView.ListMode)
        self.e2List.setObjectName("e2List")
        self.horizontalLayout_4.addWidget(self.e2List)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.acceptButton = QtWidgets.QPushButton(videoWidget)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_5.addWidget(self.acceptButton)
        self.declineButton = QtWidgets.QPushButton(videoWidget)
        self.declineButton.setObjectName("declineButton")
        self.horizontalLayout_5.addWidget(self.declineButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(videoWidget)
        self.acceptButton.clicked.connect(videoWidget.accept)
        self.declineButton.clicked.connect(videoWidget.reject)
        QtCore.QMetaObject.connectSlotsByName(videoWidget)

    def retranslateUi(self, videoWidget):
        _translate = QtCore.QCoreApplication.translate
        videoWidget.setWindowTitle(_translate("videoWidget", "Form"))
        self.previousButton.setText(_translate("videoWidget", "previous"))
        self.nextButton.setText(_translate("videoWidget", "next"))
        self.gotoButton.setText(_translate("videoWidget", "goto"))
        self.setE1Button.setText(_translate("videoWidget", "set E1"))
        self.gotoE1Button.setText(_translate("videoWidget", "goto E1"))
        self.setE2Button.setText(_translate("videoWidget", "set E2"))
        self.gotoE2Button.setText(_translate("videoWidget", "goto E2"))
        self.currentFrameLabel.setText(_translate("videoWidget", "TextLabel"))
        self.event1Label.setText(_translate("videoWidget", "TextLabel"))
        self.event2Label.setText(_translate("videoWidget", "TextLabel"))
        self.acceptButton.setText(_translate("videoWidget", "accept"))
        self.declineButton.setText(_translate("videoWidget", "decline"))


from .qtpromotion import CVVideoWidget
