# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: appveyor.yml

    -   id: check-json
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        name: pylint36
        language_version: python3.6
        additional_dependencies:
          - pytest
          - requests
          - requests-mock

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v1.9.1
    hooks:
    -   id: pylint
        name: pylint27
        language_version: python2.7
        additional_dependencies:
          - pytest
          - requests
          - requests-mock

-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
