[tool.poetry]
name = "django_jinja_helpers"
version = "0.1.3"
description = "Helpers for using django-jinja"
authors = ["Enrico Barzetti <enricobarzetti@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/enricobarzetti/django_jinja_helpers"
license = "mit"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.4"
django-crispy-forms = "^1.10.0"
django-jinja = "^2.7.0"
django-webpack-loader = "^0.7.0"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
isort = "^5.6.4"
pudb = "^2020.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
