# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from points_fl.proto import inference_pb2 as points__fl_dot_proto_dot_inference__pb2


class InferenceStub(object):
    """import "google/api/annotations.proto";
    import "proto/federated_learning.proto";

    option go_package = "./proto";
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HorizontalPredict = channel.unary_unary(
                '/Inference/HorizontalPredict',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.HorizontalPredictRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.HorizontalPredictResponse.FromString,
                )
        self.VerticalPredict = channel.unary_unary(
                '/Inference/VerticalPredict',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.VerticalPredictRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.VerticalPredictResponse.FromString,
                )
        self.CreateModel = channel.unary_unary(
                '/Inference/CreateModel',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.CreateModelRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.CreateModelResponse.FromString,
                )
        self.ReadModel = channel.unary_unary(
                '/Inference/ReadModel',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.ReadModelRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadModelResponse.FromString,
                )
        self.ReadModelList = channel.unary_unary(
                '/Inference/ReadModelList',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.ReadModelListRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadModelListResponse.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/Inference/UpdateModel',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.UpdateModelResponse.FromString,
                )
        self.DeleteModel = channel.unary_unary(
                '/Inference/DeleteModel',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.DeleteModelResponse.FromString,
                )
        self.CreateService = channel.unary_unary(
                '/Inference/CreateService',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.CreateServiceRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.CreateServiceResponse.FromString,
                )
        self.ReadService = channel.unary_unary(
                '/Inference/ReadService',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceResponse.FromString,
                )
        self.ReadServiceList = channel.unary_unary(
                '/Inference/ReadServiceList',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceListRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceListResponse.FromString,
                )
        self.DeleteService = channel.unary_unary(
                '/Inference/DeleteService',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.DeleteServiceRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.DeleteServiceResponse.FromString,
                )
        self.UpdateService = channel.unary_unary(
                '/Inference/UpdateService',
                request_serializer=points__fl_dot_proto_dot_inference__pb2.UpdateServiceRequest.SerializeToString,
                response_deserializer=points__fl_dot_proto_dot_inference__pb2.UpdateServiceResponse.FromString,
                )


class InferenceServicer(object):
    """import "google/api/annotations.proto";
    import "proto/federated_learning.proto";

    option go_package = "./proto";
    """

    def HorizontalPredict(self, request, context):
        """option (google.api.http) = {
        post: "/server/horizontal"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerticalPredict(self, request, context):
        """option (google.api.http) = {
        post: "/server/vertical"
        body: "*"
        };
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadModelList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadServiceList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HorizontalPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.HorizontalPredict,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.HorizontalPredictRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.HorizontalPredictResponse.SerializeToString,
            ),
            'VerticalPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.VerticalPredict,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.VerticalPredictRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.VerticalPredictResponse.SerializeToString,
            ),
            'CreateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateModel,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.CreateModelRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.CreateModelResponse.SerializeToString,
            ),
            'ReadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadModel,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadModelRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.ReadModelResponse.SerializeToString,
            ),
            'ReadModelList': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadModelList,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadModelListRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.ReadModelListResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.UpdateModelRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.UpdateModelResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.DeleteModelRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.DeleteModelResponse.SerializeToString,
            ),
            'CreateService': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateService,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.CreateServiceRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.CreateServiceResponse.SerializeToString,
            ),
            'ReadService': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadService,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceResponse.SerializeToString,
            ),
            'ReadServiceList': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadServiceList,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceListRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.ReadServiceListResponse.SerializeToString,
            ),
            'DeleteService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteService,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.DeleteServiceRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.DeleteServiceResponse.SerializeToString,
            ),
            'UpdateService': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateService,
                    request_deserializer=points__fl_dot_proto_dot_inference__pb2.UpdateServiceRequest.FromString,
                    response_serializer=points__fl_dot_proto_dot_inference__pb2.UpdateServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """import "google/api/annotations.proto";
    import "proto/federated_learning.proto";

    option go_package = "./proto";
    """

    @staticmethod
    def HorizontalPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/HorizontalPredict',
            points__fl_dot_proto_dot_inference__pb2.HorizontalPredictRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.HorizontalPredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerticalPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/VerticalPredict',
            points__fl_dot_proto_dot_inference__pb2.VerticalPredictRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.VerticalPredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/CreateModel',
            points__fl_dot_proto_dot_inference__pb2.CreateModelRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.CreateModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/ReadModel',
            points__fl_dot_proto_dot_inference__pb2.ReadModelRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.ReadModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadModelList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/ReadModelList',
            points__fl_dot_proto_dot_inference__pb2.ReadModelListRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.ReadModelListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/UpdateModel',
            points__fl_dot_proto_dot_inference__pb2.UpdateModelRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.UpdateModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/DeleteModel',
            points__fl_dot_proto_dot_inference__pb2.DeleteModelRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.DeleteModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/CreateService',
            points__fl_dot_proto_dot_inference__pb2.CreateServiceRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.CreateServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/ReadService',
            points__fl_dot_proto_dot_inference__pb2.ReadServiceRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.ReadServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadServiceList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/ReadServiceList',
            points__fl_dot_proto_dot_inference__pb2.ReadServiceListRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.ReadServiceListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/DeleteService',
            points__fl_dot_proto_dot_inference__pb2.DeleteServiceRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.DeleteServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Inference/UpdateService',
            points__fl_dot_proto_dot_inference__pb2.UpdateServiceRequest.SerializeToString,
            points__fl_dot_proto_dot_inference__pb2.UpdateServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
