
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-18T10:11:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "01de3d4c8c41628c775f7dc71d5a59901cd821e6",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
