[tool.poetry]
name = "antipattern_mitigation"
version = "0.1.0"
description = ""
authors = ["ulfet <ulfet.rwth@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
uvicorn = "^0.13.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-mypy = "^0.8.0"
pytest-cov = "^2.10.1"
pytest-pydocstyle = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
