[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "mstools"
author = "Exneyder A. Montoya-Araque"
author-email = "eamontoyaa@gmail.com"
home-page = "https://github.com/eamontoyaa/mstools"
description-file = "README.rst"
requires = ['numpy >= 1.19.1']
requires-python = ">=3.6"
classifiers=[
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.flit.metadata.urls]
Documentation = "https://mstools.readthedocs.io"

[tool.flit.sdist]
include = ["doc/"]
exclude = ["doc/_build"]