# Generated by Django 3.0.11 on 2020-12-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerAuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_table', models.CharField(max_length=128)),
                ('object_pk', models.IntegerField()),
                ('object_payload', models.TextField()),
                ('audit_entry_created', models.DateTimeField(auto_now_add=True)),
                ('audit_txid_current', models.BigIntegerField()),
                ('audit_operation', models.CharField(max_length=32)),
                ('audit_version', models.IntegerField()),
            ],
            options={
                'db_table': 'trigger_audit_entries_v1',
                'managed': False,
            },
        ),
    ]
