# Generated by Django 3.0.11 on 2020-12-20 15:54

from django.db import migrations

CREATE_TABLE_SQL = """
CREATE TABLE "trigger_audit_entries_v1" (
    "id"                    serial NOT NULL PRIMARY KEY,
    "object_table"          varchar(128) NOT NULL,
    "object_pk"             integer NOT NULL,
    "object_payload"        TEXT NOT NULL,
    "audit_entry_created"   timestamp with time zone NOT NULL DEFAULT NOW(),
    "audit_txid_current"    bigint NOT NULL,
    "audit_operation"       varchar(32) NOT NULL,
    "audit_request_info"    TEXT NULL,
    "audit_version"         integer NOT NULL
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('simple_trigger_audit', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(CREATE_TABLE_SQL)
    ]
