[tool.poetry]
name = "confdoggo"
version = "0.1.0-alpha"
description = "Your personal configuration doggo."
authors = ["Daniele Parmeggiani <git@danieleparmeggiani.me>"]

[tool.poetry.dependencies]
python = "^3.6"
pydantic = ">=1.6.1"
watchdog = { version = "^0.10.3", optional = true }
PyYAML = { version = "^5.3.1", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^3.4"
black = "^20.8b1"

[tool.poetry.extras]
fs-watcher = ["watchdog"]
yaml = ["PyYAML"]
