[tool.poetry]
name = "radcad"
version = "0.1.2"
description = ""
authors = ["Benjamin Scholtz <ben@bitsofether.com>"]
include = ["core/output/radCAD.*"]
packages = [
    { include = "radcad" },
    { include = "core/output/radCAD.*" },
]

[tool.poetry.dependencies]
python = "^3.8"
pathos = "^0.2.7"
ray = "^1.1.0"
pandas = "^1.1.5"
boto3 = "^1.16.43"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
cadCAD = "^0.4.23"
coveralls = "^2.2.0"
pytest-cov = "^2.10.1"
pytest-benchmark = "^3.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
