[tool.poetry]
name = "segmentation-dxf"
version = "0.3.0"
description = ""
authors = ["elisaAiwizo <elisa@aiwizo.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.4"
Pillow = "^8.0.1"
matplotlib = "^3.3.3"
more-itertools = "^8.6.0"
ezdxf = "^0.14.2"
opencv-python = "^4.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.1.2"
rstcheck = "^3.3.1"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
