[tool.poetry]
authors = ["m09 <142691+m09@users.noreply.github.com>"]
classifiers = ["Topic :: Software Development :: Build Tools"]
description = "Tool to handle invoices."
homepage = "https://github.com/m09/invoicez"
license = "Apache-2.0"
name = "invoicez"
readme = "README.md"
version = "3.0.0"

[tool.poetry.dependencies]
GitPython = "^3.1.0"
Jinja2 = "^2.11.1"
PyYAML = "^5.3.1"
click = "^7.1.1"
coloredlogs = "^14.0"
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mypy = "^0.770"
"pdfminer.six" = "^20200402"
pylint = "^2.4.4"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"

[tool.poetry.scripts]
invoicez = 'invoicez.cli:cli'

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
