[tool.poetry]
name = "poetry-demo-singein"
version = "0.1.0"
description = ""
authors = ["Singein <singein@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pendulum = "^2.1.2"
requests = "^2.25.1"
django = "^3.1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"