# coding: utf-8

"""
    Registry of Open Community Challenge API

    The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA   # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import roccclient
from roccclient.api.person_api import PersonApi  # noqa: E501
from roccclient.rest import ApiException


class TestPersonApi(unittest.TestCase):
    """PersonApi unit test stubs"""

    def setUp(self):
        self.api = roccclient.api.person_api.PersonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_person(self):
        """Test case for create_person

        Create a person  # noqa: E501
        """
        pass

    def test_delete_person(self):
        """Test case for delete_person

        Delete a person  # noqa: E501
        """
        pass

    def test_get_person(self):
        """Test case for get_person

        Get a person  # noqa: E501
        """
        pass

    def test_list_persons(self):
        """Test case for list_persons

        Get all persons  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
