# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            sudo apt-get install -y locate
            sudo apt-get install -y libgsl-dev
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r requirements-dev.txt

      # Step 3: install nPDyn
      - run:
          name: install nPDyn
          command: |
            . venv/bin/activate
            python3 setup.py install
            cp build/lib*/nPDyn/lib/*.so nPDyn/lib/

      # Step 4: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 nPDyn --statistics
            pytest nPDyn

      # Step 5: run codecov
      - run:
          name: run codecov
          command: |
            . venv/bin/activate
            bash <(curl -s https://codecov.io/bash)
