[tool]
[tool.poetry]
name = "smart_alpha"
version = "0.0.1"
homepage = "https://github.com/amazingvince/smart_alpha"
description = "Top-level package for Smart Alpha."
authors = ["Vincent Haines <amazingvince@gmail.com>"]
readme = "README.rst"
license =  "Apache-2.0"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
packages = [
    { include = "smart_alpha" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python =  "^3.5"

[tool.poetry.dev-dependencies]
bumpversion = "*"
coverage = "*"
flake8 = "*"
invoke = "*"
isort = "*"
pylint = "*"
pytest = "*"
sphinx = "*"
tox = "*"
yapf = "*"



[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
