dist: xenial   # required for Python >= 3.7

language: python

cache: pip

sudo: false

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=2.2 }
    - { python: "3.6", env: DJANGO=3.0 }
    - { python: "3.6", env: DJANGO=3.1 }

    - { python: "3.7", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=3.0 }
    - { python: "3.7", env: DJANGO=3.1 }

    - { python: "3.8", env: DJANGO=2.2 }
    - { python: "3.8", env: DJANGO=3.0 }
    - { python: "3.8", env: DJANGO=3.1 }

    - { python: "3.8", env: TOXENV=coverage }

install:
  - pip install tox tox-venv tox-travis

script:
  - tox

notifications:
  email:
    false
  slack:
    secure: QKqSaM/Om3Lem5H9OgT9EdgOXtkLEaZq6b7UTMrYFVkQkss2FXiPPRmO3uieWA8uAAqq5qaDzko2FMiJ4icGeL5wPVRI9SihyR3/5YlLQV5itr/TANjy8Dhf3rlToAqiuiwkSKLSxA96RpT9n+it3TzHoFGPJwTTnBfaWo85RyoirVBc792W3gnQyAHD6YNO+sMvB12W9BBIeXUp3k+4+0C6uB/HPOGfTtko7Z/GtohAPejlu+4i9x4oPDWBFmRM2gsrjUlSR9iocM+rlMWv/Y1Tdf8oNfEulybVb+4+5u59LGK8tU/QImx5NlxgaedYM62lnI1XDIbFTpURtJHTz2ng9ga1p0+GtOmkzaa4N/YT5U3We8TJUJbXm/PSlZ6wLNk6v1Jx5JNbc2gZgBu6as6G4EjpcyUjkTZ3pefD5s4+uVZzBM57t2OYetuMNO55rcy3aTPqSph1Y+kdQ5FAj2TnyHaEIFHqWdOF/rOXWtxb3cMl/V1my1nh/FurlXt/gRQz1XnVglVsz3ZWEB/W+R8ZcqEPrYEcGuoJqOyBirjcl2xkfllAYhY8/dEcauWtfAh8djl3lLxB8MRZbtB45zJxz65UTGtIhwlNYZC6YbAB7tuBBBi+HTHaaIQvZgI7rK+5AQrgGZV4ktYOQHSyQVyYEZSFNgdD8m+znCteYPU=
