
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-29T21:19:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "36835744080edd3d56d693df47bb5d33739fb4da",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
