
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-26T17:42:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ae753a6c9654cb1b1473313bb7362fc24e79582",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
