[tool.poetry]
name = "roci"
version = "0.2.1"
description = "no longer a work horse"
authors = ["Andrew Blance <andrewblance@live.co.uk>"]
license = "MIT"

readme = "README.md"

repository = "https://github.com/andrewblance/roci"

keywords = ["packaging", "project templates", "projects", "roci"]

classifiers = [
    "Programming Language :: Python",
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
roci = 'roci:direc_dumper'
