[tool.poetry]
name = "vag"
version = "0.1.11"
description = "vagrant utility cli tool"
authors = ["Seven Tella <7onetella@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
Click = "^7.1.2"
untangle = "^1.1.1"
jinja2 = "^2.11.2"

[tool.poetry.scripts]
vag = "vag.console.application:main"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
