active_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
  - verb: fill
    name: first_and_last_name
    locators:
      - mode: id
        value: name
        index: 0
        score: 0.0
      - mode: name
        value: name
        index: 0
        score: 0.0
