image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/

stages:
  - build
  - test
  - deploy

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

install:
  stage: build
  script:
  - pip install .

lint:
  stage: test
  script:
  - pip install --upgrade flake8 isort mypy
  - flake8 --exclude .venv --max-line-length=88
  - isort --check --diff .
  - mypy **/*.py

black:
  stage: test
  script:
  - pip install black
  - shopt -s globstar
  - black --check **/*.py

deploy:
  stage: deploy
  only:
  - tags
  script:
  - pip install twine wheel
  - python3 setup.py check sdist bdist_wheel
  - twine upload dist/*
