name: Run unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 12, 13, 14 ]
    name: Java {% raw %}${{ matrix.java }}{% endraw %}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: {% raw %}${{ matrix.java }}{% endraw %}

      # Disabled until Github Actions finds a way to allow GUIs to run
      # Our GUI unit tests would result in errors
      #- name: Run tests
      #  run: mvn clean verify
