[tool.poetry]
name = "ses-log-handler"
packages = [
    {include = "ses_log_handler"}
]
version = "1.0.2"
description = "Log messages to email via Amazon SES"
authors = ["Matt Pye <pyematt@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/pyepye/ses-log-handler"
homepage = "https://github.com/pyepye/ses-log-handler"
keywords = ["logging", "AWS", "SES", "Simple Email Service"]


[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.0.0"


[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.10.1"
pytest-freezegun = "^0.4.2"
pytest-mock = "^3.4.0"
isort = "^5.6.4"
flake8 = "^3.8.4"
mypy = "^0.790"
tox = "^3.20.1"


[tool.isort]
line_length = 79
multi_line_output = 5
known_third_party = "pytest"
known_first_party = "ses_log_handler"
skip_glob = "__pycache__/*,venv/*,.venv/*,.tox/*,.mypy_cache"


[tool.pytest.ini_options]
addopts = "--cov=ses_log_handler/ --cov-report html --cov-report term"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
