[tool.poetry]
name = "fluf"
version = "0.1.9"
description = "Simple caching & workflow"
authors = ["Mark Fiers <mark.fiers.42@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dill = "^0.3.3"
matplotlib = "^3.3.3"
peewee = "^3.14.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
