[build-system]
requires = ['setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-grid<=2.8.0.dev20201218', 'UFL==2017.1.0', 'dune-alugrid<=2.8.0.dev20201218', 'dune-istl<=2.8.0.dev20201218', 'dune-localfunctions<=2.8.0.dev20201218']
build-backend = 'setuptools.build_meta'
