[tool.poetry]
name = "keynote_highlight"
version = "0.0.2"
description = "Code highlighter with preset, but customizable settings"
authors = ["Nikita Churikov <nikita@chur.ru>"]
license = "MIT"
readme="README.md"
homepage="https://github.com/churnikov/keynote-highlight"

[tool.poetry.dependencies]
python = "^3.9"
Pygments = "^2.7.3"
pyperclip = "^1.8.1"
click = "^7.1.2"
black = "^20.8b1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.9.3"

[tool.poetry.scripts]
keyhi = 'keynote_highlight.main:main'

[tool.black]
line-length = 100
target_version = ["py38"]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
