[tool.poetry]
name = "galaxy-fds-sdk"
version = "1.4.38"
description = "Python sdk for Galaxy FDS"
authors = ["hujianxin <hujianxin@xiaomi.com>"]
packages = [
    { include = "fds" },
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
requests = "^2.21"
argcomplete = "^1.9"
click = "^7.0"
enum34 = { version = "*", python = "~3.4" }
pathlib2 = { version = "^2.2", python = "~2.7", allow-prereleases = true }
futures = { version = "*", python = "~2.7", allow-prereleases = true }
crcmod = "^1.7"

[tool.poetry.dev-dependencies]
rope = "^0.14.0"
pep8 = "^1.7"
autopep8 = "^1.4"

[tool.poetry.scripts]
fds = 'fds.fds_cli:main'
fdscli = 'fds.fdscli_cli:main'

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

