[tool.poetry]
name = "fastapi-jsonrpc"
version = "1.1.2"
description = "JSON-RPC server based on fastapi"
license = "MIT"
authors = ["Sergey Magafurov <magafurov@tochka.com>"]
readme = "README.rst"
repository = "https://github.com/smagafurov/fastapi-jsonrpc"
homepage = "https://github.com/smagafurov/fastapi-jsonrpc"
keywords = ['json-rpc', 'asgi', 'swagger', 'openapi', 'fastapi', 'pydantic', 'starlette']
exclude = ["example1.py", "example2.py"]

[tool.poetry.dependencies]
python = "^3.6"
aiojobs = "^0.2.2"
fastapi = ">0.55"

[tool.poetry.dev-dependencies]
uvicorn = "^0.8.6"
pygments = "^2.4"
rst_include = "^2.1.0"
pytest = "^5.2.2"
# python-dateutil 2.8.1 needs six but has no dependency
six = "^1.15.0"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
