exclude: 'versioneer.py|nPDyn/_version.py|docs/source/conf.py|^build/|^dist/|^htmlcov/|^nPDyn.egg-info/|$__.py'

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    -   id: pyupgrade
        # for now don't force to change from %-operator to {}
        args: [--keep-percent-format, --py3-plus]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: mixed-line-ending

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [nPDyn --config .flake8]
        additional_dependencies: [flake8-deprecated, flake8-mutable]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell
        files: '.py|.rst'
        exclude: 'doc/doc_examples_to_gallery.py'
        # escaped characters currently do not work correctly
        # so \nnumber is considered a spelling error....
        args: [-L nnumber]

-   repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
    -   id: yesqa

-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
        args: [-l 79]
