active_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
actions:
  - verb: click
    name: stronger
    locators:
      - mode: id
        value: fields[366]-1
        index: 0
        uses: 2
      - mode: text
        value: Not Stronger
        index: 0
        uses: 0
      - mode: text
        value: Not stronger
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: first_name
        index: 0
        uses: -1
      - mode: name
        value: first-name
        index: 0
        uses: -1
      - mode: id
        value: first_name
        index: 0
        uses: -1
      - mode: id
        value: first-name
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="First Name"]'
        index: 0
        uses: -1
      - mode: name
        value: fields[383]
        index: 0
        uses: 2
  - verb: fill
    name: last_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: last_name
        index: 0
        uses: -1
      - mode: name
        value: last-name
        index: 0
        uses: -1
      - mode: id
        value: last_name
        index: 0
        uses: -1
      - mode: id
        value: last-name
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Last Name"]'
        index: 0
        uses: -1
      - mode: name
        value: fields[384]
        index: 0
        uses: 2
  - verb: fill
    name: email
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: email
        index: 0
        uses: -1
      - mode: name
        value: email
        index: 0
        uses: -1
      - mode: id
        value: email
        index: 0
        uses: -1
      - mode: id
        value: email
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Email"]'
        index: 0
        uses: -1
      - mode: name
        value: fields[386]
        index: 0
        uses: 2
  - verb: fill
    name: zip
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: zip
        index: 0
        uses: -1
      - mode: name
        value: zip
        index: 0
        uses: -1
      - mode: id
        value: zip
        index: 0
        uses: -1
      - mode: id
        value: zip
        index: 0
        uses: -1
      - mode: css
        value: '[aria-label="Zip"]'
        index: 0
        uses: -1
      - mode: name
        value: fields[385]
        index: 0
        uses: 2
  - verb: click
    name: record_my_vote
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Record My Vote
        index: 0
        uses: -1
      - mode: text
        value: Record my vote
        index: 0
        uses: -1
      - mode: name
        value: respond
        index: 0
        uses: 2
  - verb: click
    name: reelected
    locators:
      - mode: id
        value: fields[367]-1
        index: 0
        uses: 2
      - mode: text
        value: Not Reelected
        index: 0
        uses: 0
      - mode: text
        value: Not reelected
        index: 0
        uses: 0
  - verb: click
    name: mainstream
    locators:
      - mode: id
        value: fields[370]-1
        index: 0
        uses: 2
      - mode: text
        value: Mainstream
        index: 0
        uses: 0
      - mode: text
        value: Mainstream
        index: 0
        uses: 0
  - verb: click
    name: media
    locators:
      - mode: id
        value: fields[371]-1
        index: 0
        uses: 2
      - mode: text
        value: Media
        index: 0
        uses: 0
      - mode: text
        value: Media
        index: 0
        uses: 0
  - verb: click
    name: message
    locators:
      - mode: id
        value: fields[372]-0
        index: 0
        uses: 2
      - mode: text
        value: Message
        index: 0
        uses: 0
      - mode: text
        value: Message
        index: 0
        uses: 0
  - verb: click
    name: twitter
    locators:
      - mode: id
        value: fields[374]-1
        index: 0
        uses: 2
      - mode: text
        value: Twitter
        index: 0
        uses: 0
      - mode: text
        value: Twitter
        index: 0
        uses: 0
  - verb: click
    name: vote
    locators:
      - mode: id
        value: fields[378]-1
        index: 0
        uses: 2
      - mode: text
        value: Vote
        index: 0
        uses: 0
      - mode: text
        value: Vote
        index: 0
        uses: 0
