# -*- coding: utf-8 -*-

"""
    md_notes_cc

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from md_notes_cc.api_helper import APIHelper
import md_notes_cc.exceptions.api_exception

class OAuthProviderException(md_notes_cc.exceptions.api_exception.APIException):
    def __init__(self, reason, context):
        """Constructor for the OAuthProviderException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            context (HttpContext):  The HttpContext of the API call.

        """
        super(OAuthProviderException, self).__init__(reason, context)
        dictionary = APIHelper.json_deserialize(self.context.response.raw_body)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error = dictionary.get('error')
        self.error_description = dictionary.get('error_description')
        self.error_uri = dictionary.get('error_uri')
