[tool.poetry]
name = "delta-lake-reader"
version = "0.1.0"
description = ""
authors = ["Jeppe Johan Waarkjær Olsen <jeppe742@gmail.com>"]
packages= [{include="deltalake"}]
readme = "README.md"
repository = "https://github.com/jeppe742/DeltaLakeReader/actions"

[tool.poetry.dependencies]
python = "^3.7"
pyarrow = "^2.0.0"
azure-storage-blob = "^12.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
mypy = "^0.790"
isort = "^5.6.4"
black = "^20.8b1"
tox = "^3.20.1"
pyspark = "^3.0.1"
pandas = "^1.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
