active_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    score: 0.5
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.5
  - verb: click
    name: submit
    locators:
      - mode: ''
        value: ''
        index: 0
        score: 0.25
      - mode: id
        value: btn_submit
        index: 0
        score: 0.25
      - mode: text
        value: Submit
        index: 0
        score: 0.25
