viewer:
  blur_amount: 12                         # default=12,  larger values than 12 will increase processing load quite a bit
  blur_zoom: 1.0                          # default=1.0, must be >= 1.0 which expands the backgorund to just fill the space around the image"
  blur_edges: False                       # default=False, use blurred version of image to fill edges - will override FIT = False"
  edge_alpha: 0.5                         # default=0.5, background colour at edge. 1.0 would show reflection of image
  fps: 20.0                               # default=20.0
  background: [0.2, 0.2, 0.3, 1.0]        # default=[0.2, 0.2, 0.3, 1.0], RGBA to fill edges when fitting
  blend_type: 0.0                         # default="blend", choices={"blend":0.0, "burn":1.0, "bump":2.0}, type of blend the shader can do"
  font_file: "~/.local/picframe/data/fonts/NotoSans-Regular.ttf"
  shader: "~/.local/picframe/data/shaders/blend_new"
  show_names_tm: 0.0                      # default=0.0, time to show text over image with file name
  fit: False                              # default=False, shrink to fit screen (i.e. don't crop")
  auto_resize: True                       # default=True, set this to False if you want to use 4K resolution on Raspberry Pi 4. 
                                          # You should ensure your images are the correct size for the display")
  kenburns: False                         # default=False, will set fit->False and blur_edges->False"
  
model:
  pic_dir: "~/Pictures"                   # default="~/Pictures", root folder for images
  no_files_img: "~/.local/picframe/data/no_pictures.jpg" # default="PictureFrame2020img.jpg", image to show if none selected
  subdirectory: ""                        # default="", subdir of pic_dir - can be changed by MQTT"
  check_dir_tm: 60.0                      # default=60.0, time in seconds between checking if the image directory has changed
  recent_n: 3                             # default=3, when shuffling the keep n most recent ones to play before the rest
  reshuffle_num: 1                        # default=1, times through before reshuffling
  time_delay: 200.0                       # default=200.0, time between consecutive slide starts - can be changed by MQTT
  fade_time: 10.0                         # default=10.0, change time during which slides overlap - can be changed by MQTT"
  shuffle: True                           # default=True, shuffle on reloading image files - can be changed by MQTT"
  image_attr: [                           # image attributes send by MQTT, Keys are taken from exifread library, 'PICFRAME GPS' is special to retrieve GPS lon/lat
    'PICFRAME GPS', 
    'EXIF FNumber', 
    'EXIF ExposureTime', 
    'EXIF ISOSpeedRatings', 
    'EXIF FocalLength', 
    'EXIF DateTimeOriginal', 
    'Image Model']

mqtt:                                     
  server: "your_mqtt_broker"              # No defaults for server
  port: 8883                              # derfault=8883 for tls, 1883 else (tls must be "" then !!!!!)
  login: "name"                           # your mqtt user
  password: "your_password"               # password for mqtt user
  tls: "/path/to/your/ca.crt"             # filename including path to your ca.crt. If not used, must be set to "" !!!!
  device_id: 'picframe'                   # default='picframe' unique id of device. change if there is more than one picture frame
