.zhihu.:
  must_contain_part: p
feministcurrent:
  not_contain:
    - podcast
    - whats-current
wemp.app:
  must_contain_part: posts
ed.ted.com:
  must_contain_part: lessons
gonghao51:
  not_contain:
    - guaishi
thepaper:
  must_contain: newsDetail_forward
thinkingtaiwan:
  must_contain_part: content
twreporter:
  must_contain_part: a
udn.com:
  must_contain_part: story
philomedium:
  must_contain_part: blog
matters:
  not_contain:
    - johngalt
    - rein/
    - lliinngg
    - arkincollapse
    - Maneki
    - cherryyoko
    - chdwong
    - XiaoFan
    - mikejohn
    - usbecomes1984
    - hk1980
    - chyi/
    - xhzhang/
    - wanzhic
    - like-coin
    - wudunyi
    - gu1943
    - likecoin
    - liker-land
  sig_len: 
    - 60
    - 50
coollou:
  must_contain_part: node
www.greenpeace.org/:
  must_contain_part: update
www.biede.com:
  not_contain:
    - name/
    - tag/