
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-26T19:03:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4f57acf319e3ea9bd384a02281f50c08f4eecfc",
 "version": "v0.22.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
