[tool.poetry]
name = "py-cdk-utils"
version = "1.0.0"
description = "Utilities to assist with building Python-based applications in AWS-CDK"
authors = ["Greg Farrow <greg.farrow1@gmail.com>"]
license = "MIT"

[tool.semantic_release]
version_variable = "src/py_cdk_utils/__init__.py:__version__"
version_source = "tag"
branch = "main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.10.1"
pytest-html = "^3.1.1"
pytest-mock = "^3.4.0"
python-semantic-release = "^7.8.2"
black = "^20.8b1"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
