INPUT_IMAGES_DIR: '/data/tool/pole/mapillary/data/images/'
INPUT_LABELS_DIR: '/data/tool/pole/mapillary/data/labels/'
OUTPUT_DIR: '/data/tool/pole/mapillary/output/'
CLASS_TYPE:
    139101: 50
    139103: 180 
    139104: 250