[tool.poetry]
name = "web_error"
version = "0.4.2"
description = "Web based error utils"
authors = ["Daniel Edgecombe <edgy.edgemond@gmail.com>"]
license = "Apache-2.0"
repository="https://github.com/EdgyEdgemond/web-error/"
homepage="https://github.com/EdgyEdgemond/web-error/"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

aiohttp = "*"
pyramid = "*"
flask = "*"
fastapi = "*"

changelog-gen = "~0.7.0"
flake8 = "^3.7"
flake8-commas = "^2.0"
flake8-isort = "^2.7"
flake8-quotes = "^2.1"
isort = "^4.3"
pytest = "^5.2"
pytest-asyncio = "*"
pytest-cov = "^2.8"
pytest-git = "^1.7.0"
pytest-random-order = "^1.0"

[build-system]
requires = ["poetry>=1.1,<2.0"]
build-backend = "poetry.masonry.api"
