version: "2"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 15

plugins:
  sonar-python:
    enabled: true
    config:
      test_patterns:
        - "tests/*.py"
    checks:
      python:S3776:
        enabled: false
      python:S107:
        enabled: false
      python:S1542:
        enabled: false

  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

  markdownlint:
    enabled: true
    issue_override:
      severity: minor

exclude_patterns:
- "src/metpy/io/_nexrad_msgs/msg*.py"
- "src/metpy/io/metar_parse.peg"
- "src/metpy/io/metar_parser.py"
- "docs/**/*"
- "staticdata/**/*"
- "tests/*/baseline/*"
- "src/metpy/plots/fonts/*.ttf"
- "src/metpy/plots/_static/*.png"
- "talks/*.pdf"
