# Generated by Django 3.1.3 on 2020-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sso_auth', '0002_auto_20201123_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='oauth_user_set', related_query_name='oauth_user', to='auth.Group', verbose_name='groups'),
        ),
    ]
