
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T16:08:49+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7e569aedd5a2a9230dc5b1c2857866a34d02db4",
 "version": "0.0.71.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
