# Generated by Django 2.0.5 on 2018-05-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('iddist', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='IDDist')),
                ('coddist', models.CharField(db_index=True, max_length=2, verbose_name='Código Distrito')),
                ('nom_dist', models.CharField(max_length=50, verbose_name='Distrito')),
            ],
            options={
                'ordering': ('prov__dpto__nom_dpto', 'prov__nom_prov', 'nom_dist'),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprov', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='IDProv')),
                ('codprov', models.CharField(max_length=2, verbose_name='Código Provincia')),
                ('nom_prov', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
            options={
                'ordering': ('dpto__nom_dpto', 'nom_prov'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('coddpto', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nom_dpto', models.CharField(max_length=50, verbose_name='Región')),
            ],
            options={
                'ordering': ('nom_dpto',),
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeos.Region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='prov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubigeos.Provincia', verbose_name='Provincia'),
        ),
    ]
