
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-27T02:38:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d09b97238b100303f726d3213531d6f441f53f6a",
 "version": "0.5.dev2052"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
