[tool.poetry]
name = "python_wise_utils"
version = "0.3.4"
description = "Python interpreter convenience utilities"
authors = ["Wisdom Wolf <wisdomwolf@gmail.com>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/WisdomWolf/python_wise_utils"
repository = "https://github.com/WisdomWolf/python_wise_utils"

[tool.poetry.dependencies]
python = "==3.*,>=3.6.0"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
dephell = "==0.*,>=0.8.3"
neovim = "==0.*,>=0.3.1"
ipython = "==7.*,>=7.16.1"
keyring = "==21.*,>=21.2.1"
"keyrings.cryptfile" = "==1.*,>=1.3.4"












[tool.dephell.main]
# read from poetry format
from = {format = "poetry", path = "pyproject.toml"}
versioning = "zerover"
to = {format = "poetry", path = "pyproject.toml"}
tag = "v."


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
