version: 2
jobs:
    build:
     docker:
        - image: python:3.8
          environment:
     steps:
        - checkout
        - run:
            name: deps
            command: |
                #apt install python-pip
                pip install --user --upgrade -r requirements.txt

        - run:
            name: build
            command: |
                python setup.py install --user

        - run:
            name: dts help
            command: |
                 export PATH=/home/circleci/.local/bin:$PATH
                 dts help

        - run:
            name: dts version
            command: |
                 export PATH=/home/circleci/.local/bin:$PATH
                 dts version
#
#        - run:
#            name: dts aido token
#            command: |
#               export PATH=/home/circleci/.local/bin:$PATH
#               dts aido18 token dt1-XXzMstGtdJhJeXv-43dzqWFnWd8KBa1yev1g3UKnzVxZkkTbfQj2vduBXhfPjK6FSSCHQZPr986b8tXASH || true
