[tool.poetry]
name = "dyncfg"
version = "0.0.1"
description = "Simples and powerful configuration engine"
authors = ["Rodrigo Pinheiro Matias <rodrigopmatias@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.3.1"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
