import ufl
import sympy

ufl_trans = {"  sqrt" : ufl.sqrt,
                "sin":ufl.sin ,
                "atan2":ufl.atan_2 ,
                "cos":ufl.cos,
                "sqrt" : (lambda x : ufl.algebra.Power(x,0.5)+0.0001) ,
                "tan":ufl.tan ,
                "pi": ufl.pi,
                "Abs": ufl.algebra.Abs,
                "exp" : ufl.exp,
                "log" : ufl.ln,
                "erf" : ufl.erf,
                "acos":ufl.acos,
                "asin":ufl.asin,
                "atan":ufl.atan,
                "acosh":ufl.cosh,
                "asinh":ufl.sinh,
                "atanh" :ufl.tanh,
                "pi" : ufl.pi,
                }

ufl_trans_rev = {   "sqrt":sympy.sqrt,
                    "sin" : sympy.sin,
                    "atan_2" : sympy.atan2,
                    "cos" : sympy.cos,
                    "tan" : sympy.tan,
                    "pi" : sympy.pi,
                    "Abs" : sympy.Abs,
                    "exp" : sympy.exp,
                    "log" : sympy.ln,
                    "erf" : sympy.erf,
                    "acos" : sympy.acos ,
                    "asin" : sympy.asin ,
                    "atan" : sympy.atan,
                    "acosh" : sympy.acosh ,
                    "asinh" : sympy.sinh,
                    "atanh" : sympy.atanh,
                }
