
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-19T13:17:00-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a11ae816abf8ed8b3f1449d7469d0fe77f09a615",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
