[tool.poetry]
name = "dsafe-fiber"
version = "0.1.0"
description = "Smart Contract Monitoring SDK"
authors = ["Robin Raymond <robin@robinraymond.de>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "fiber" },
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.7.3"
SQLAlchemy = "^1.3.22"
sqlalchemy-stubs = "^0.3"
psycopg2-binary = "^2.8.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"
alembic = "^1.4.3"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.messages_control]
disable = "C0330, C0326, R0903, R0401, C0414, R0801"

[tool.pylint.format]
max-line-length = "88"

[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true
known_first_party = ["fiber"]
