[tool.poetry]
name = "pre_notifier"
version = "0.1.3"
description = ""
authors = ["Ivan Kuznetsov <tikerlade@gmail.com>"]

[project.entry-points]
pre_notifier = "pre_notifier.__main__:main"


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
