[tool.poetry]
name = "tbk_api"
version = "0.2.1"
description = "淘宝客接口"
readme = "README.md"
authors = ["dev <dev@qiyutech.tech>"]

[tool.poetry.dependencies]
python = "^3.9"

pydantic = ">=1.7,<2"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
