[tool.poetry]
name = "roci"
version = "0.2.0"
description = "no longer a work horse"
authors = ["Andrew Blance <andrewblance@live.co.uk>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
roci = 'roci:direc_dumper'
