dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  #- "nightly"  # nightly build
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
# command to run tests
script: 
  - pytest -q ./datapungibea/tests/test_driversCI.py --cmdopt=$pyTvar --maxfail=2
  
  
