active_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
inactive_locators:
  - mode: ''
    value: ''
    index: 0
    uses: 0
actions:
  - verb: ''
    name: ''
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
  - verb: click
    name: select
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Select
        index: 0
        uses: -1
      - mode: text
        value: Select
        index: 0
        uses: -1
      - mode: css
        value: '[data-fv-notempty-message="This field requires a value"]'
        index: 0
        uses: 3
  - verb: click
    name: no
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: No
        index: 0
        uses: 2
      - mode: text
        value: No
        index: 0
        uses: 0
  - verb: click
    name: prefix
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Prefix
        index: 0
        uses: 0
      - mode: text
        value: Prefix
        index: 0
        uses: 0
      - mode: css
        value: '[data-fv-notempty-message="This field requires a value"]'
        index: 1
        uses: 0
  - verb: click
    name: mr
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Mr.
        index: 0
        uses: 0
      - mode: text
        value: Mr
        index: 0
        uses: 0
  - verb: click
    name: mrs
    locators:
      - mode: text
        value: Mrs.
        index: 0
        uses: 0
      - mode: text
        value: Mrs
        index: 0
        uses: 0
      - mode: text
        value: Mrs
        index: 0
        uses: 0
  - verb: click
    name: mr
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Mr.
        index: 0
        uses: 0
      - mode: text
        value: Mr
        index: 0
        uses: 0
  - verb: fill
    name: first_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: first_name
        index: 0
        uses: -1
      - mode: name
        value: first-name
        index: 0
        uses: -1
      - mode: id
        value: first_name
        index: 0
        uses: -1
      - mode: id
        value: first-name
        index: 0
        uses: -1
      - mode: css
        value: '[salsa-reference-name="person-firstname"]'
        index: 0
        uses: 2
      - mode: css
        value: '[data-fv-field="field-person-firstname"]'
        index: 0
        uses: 0
  - verb: fill
    name: last_name
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: last_name
        index: 0
        uses: -1
      - mode: name
        value: last-name
        index: 0
        uses: -1
      - mode: id
        value: last_name
        index: 0
        uses: -1
      - mode: id
        value: last-name
        index: 0
        uses: -1
      - mode: css
        value: '[salsa-reference-name="person-lastname"]'
        index: 0
        uses: 2
  - verb: fill
    name: email_address
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: email_address
        index: 0
        uses: -1
      - mode: name
        value: email-address
        index: 0
        uses: -1
      - mode: id
        value: email_address
        index: 0
        uses: -1
      - mode: id
        value: email-address
        index: 0
        uses: -1
      - mode: css
        value: '[salsa-reference-name="contact-email"]'
        index: 0
        uses: 2
  - verb: fill
    name: zip_code
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: name
        value: zip_code
        index: 0
        uses: -1
      - mode: name
        value: zip-code
        index: 0
        uses: -1
      - mode: id
        value: zip_code
        index: 0
        uses: -1
      - mode: id
        value: zip-code
        index: 0
        uses: -1
      - mode: css
        value: '[salsa-reference-name="address-zip"]'
        index: 0
        uses: 2
  - verb: click
    name: vote_here
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Vote Here
        index: 0
        uses: 2
      - mode: text
        value: Vote here
        index: 0
        uses: 0
  - verb: click
    name: text_messages
    locators:
      - mode: ''
        value: ''
        index: 0
        uses: 0
      - mode: text
        value: Text Messages
        index: 0
        uses: -1
      - mode: text
        value: Text messages
        index: 0
        uses: -1
      - mode: css
        value: '[salsa-reference-name="phoneoptincb"]'
        index: 0
        uses: 2
