apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtls
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pvc.yml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: mtls
    files:
      - ./files/config.ini
  - name: mtls-admin-seeds
    files: []
  - name: mtls-user-seeds
    files: []
secretGenerator:
  - name: mtls-certs
    type: Opaque
    files:
      - ./secrets/ca.crt
      - ./secrets/ca.key
images:
  - name: drgrove/mtls-server
    newTag: v0.18.0
    digest: sha256:9e5005a18ecd09b1d0d10631b7e62a1c15b5dd22a851563f88c05eb7c588c815
