name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: ci-skip-step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[ci skip];[ci-skip];[skip ci];[skip-ci]'
          commit-filter-separator: ';'

  build:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 4
      matrix:
        python: [3.7, 3.8]  # , 3.9]
        os: [ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
        exit-code: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions codecov

    - name: Install R
      if: matrix.os == 'ubuntu-latest' && matrix.python == '3.8'
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.3'
    - name: Get R cache dir
      uses: actions/cache@v2
      if: matrix.os == 'ubuntu-latest' && matrix.python == '3.8'
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    - name: Install OmnipathR
      if: matrix.os == 'ubuntu-latest' && matrix.python == '3.8'
      run: |
        sudo apt-get install libcurl4-openssl-dev
        sudo Rscript --vanilla -e "if (!(requireNamespace('BiocManager', quietly=TRUE))) { install.packages(c('BiocManager', 'curl'), repos='https://cloud.r-project.org/') }; BiocManager::install('OmnipathR')"
        Rscript --vanilla -e "packageVersion('OmnipathR')"

    - name: Linting
      run: |
        tox -e lint
    - name: Testing
      run: |
        tox
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: Upload coverage to Codecov
      if: success()
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        CODECOV_NAME: ${{ matrix.python }}-${{ matrix.os }}
      run: |
        codecov --no-color --required --flags unittests

    - name: Install pypa/build
      run: pip install build
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/

    - name: Publish package on PyPI
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
        skip_existing: true
        verbose: true
