
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-25T15:29:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26c58fb55cda3bfe958eeac3c5aff513f243bc65",
 "version": "2.4.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
