language: python
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create -n prysmci python=3.8 --yes
  - source activate prysmci
  - conda config --add channels conda-forge
  - >-
      conda install --yes
      numpy>=1.18
      scipy>=1.5
      astropy>=4.0.0
      matplotlib>=3.0
      scikit-image
      imageio
      pandas
      h5py
      pytest=5.4.3
      pytest-cov=2.10.0
      coveralls==2.1.1
  - pip install .
services:
  - xvfb
script:
  - pytest --cov=prysm tests/
notifications:
  email: false
after_success:
  - coveralls
