[tool.poetry]
name = "outcome-pypicloud-access-github"
version = "1.2.6"
description = "A Github-based access backend for pypicloud."
authors = ["Douglas Willcocks <douglas@outcome.co>"]
readme = "README.md"
license = "ISC"
packages = [
  { include = "outcome", from = "src" }
]
homepage = "https://github.com/outcome-co/pypicloud-access-github-py"
repository = "https://github.com/outcome-co/pypicloud-access-github-py"
documentation = "https://github.com/outcome-co/pypicloud-access-github-py#README"

[tool.poetry.dependencies]
python = "~3.8"
toml = "^0.10.1"
sgqlc = ">=10.1,<13.0"
pydash = "^4.8.0"
python-memcached = {version = "^1.59", optional = true }
outcome-utils = "^4.7.0"

[tool.poetry.extras]
memcache = ["python-memcached"]

[tool.poetry.dev-dependencies]
outcome-devkit = "3.2.1"
pytest-dotenv = "^0.5.1"
PyGithub = "^1.53"
pydantic = "^1.7"
click = "^7.1.2"
python-dotenv = "^0.15.0"
requests = "^2.25.1"
pynacl = "^1.4.0"
pypicloud = {extras = ["gcs"], version = "^1.1.7"}
uwsgi = "^2.0.19"
pastescript = "^3.2.0"
waitress = "^1.4.4"
python-memcached = "^1.59"
redis = "^3.5.3"
flaky = "^3.7.0"
tenacity = "^6.3.1"
pystache = "^0.5.4"


[tool.isort]
skip_glob = "*/.cache/**/*"

[tool.coverage.run]
branch = true
data_file = 'coverage/data'
source = ['src']
omit = ['test/*']
parallel = true
plugins = ['outcome.devkit.env_coverage']

[tool.coverage.report]
fail_under = 100
skip_empty = true
exclude_lines = ['pragma: no cover', '@abc.abstract', '@abstract']

[tool.coverage.html]
show_contexts = true
directory = 'coverage/html'

[tool.black]
line-length = 130
include = '\.pyi?$'
# This stops black from rewriting quotes
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.cache
)/
'''

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.2.6"
tag_format = "v$version"
bump_message = "chore(version): $current_version → $new_version"
version_files = ["pyproject.toml:^version", "README.md:version-badge"]

[build-system]
requires = ["poetry==1.0.10"]
build-backend = "poetry.masonry.api"

