
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-28T11:31:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "44724aae88a36b0c3484ccfc3fa86375e0672ba9",
 "version": "v1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
