dist: xenial   # required for Python >= 3.7

language: python

cache: pip

sudo: false

matrix:
  fast_finish: true
  include:

    - { python: "3.6", env: DJANGO=2.2 }
    - { python: "3.6", env: DJANGO=3.0 }
    - { python: "3.6", env: DJANGO=3.1 }

    - { python: "3.7", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=3.0 }
    - { python: "3.7", env: DJANGO=3.1 }

    - { python: "3.8", env: DJANGO=2.2 }
    - { python: "3.8", env: DJANGO=3.0 }
    - { python: "3.8", env: DJANGO=3.1 }

    - { python: "3.8", env: TOXENV=coverage }

install:
  - pip install tox tox-venv tox-travis

script:
  - tox

notifications:
  email:
    false
  slack:
    secure: loOVkhkqtVEDxdP4qTgGjCQDzzzIEZ0OjQOgYZEiTp+Qmds8W3ZeTkAh5apDSdwRPGaEfTDrOgr3Yg/4z+zOkRCyI4q2ca4y7dFiDzXy3tfP8puHBFS0sYMvuNolhTVdPtqXW7bv10xQ5970TcP1zBVbmrRt/VVQ/3zqU8SCKQpWJbN/BrkrGK6VHJ3c+CZhM6hQwsFUyx/D5+CfKf6HvigPbauwdICyTh4zLqKu/r8j0bStvIeSWe8zc5mb2Q5i/SBfVat4KFV2fBxEMO+yYuuRhJ+2hJMRGfteJM6Q4M/coAW16z+ro97omryfKHEMlK8jD/Oa+LiQLKuxfScj7yJKF69I8OdwYnJeQd9AgnBflNWw/4MsVIBgAEJEHnbwdCGVFz/4B/VyQQIjEKiBmZZ1rB/FGQiBQe5zQEia+BDPPgp3Bq+A8LjJtwLconI0k814HtLcx1QpY7Ebugqi08V1kaOYjbMrAp5efj0XcCXr00qIv/nBdMQtecfQekX//OozD00KS6KyWyj9Vxlea25s57JRKV4e7QYGKZzTz/BvzmTxLWysglnkLECmeLc69HTPgHDnRWD4TA0MXUm6bzyc8nVeZhmm6iwmaEQitgBb1IsQi24bYz93pzd4ym0NRdpr2uz/LI5qMhMkI3xjg8L0CrRJanUu/qjp/P479w4=
