[tool.poetry]
name = "jnt-django-graphene-toolbox"
version = "0.1.27"
description = ""
authors = ["Junte <tech@junte.ru>"]
classifiers=[
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Framework :: Django :: 2.0',
        'Framework :: Django :: 2.1',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.0',
        'Framework :: Django :: 3.1',
        'Topic :: Software Development :: Libraries :: Python Modules'
]

packages = [
    { include = "jnt_django_graphene_toolbox", from ="src" }
]

[tool.poetry.dependencies]
python = "^3.8"
jnt_django_toolbox = "^0.1.6"
graphene_django = "^2.10.1"
djangorestframework = "3.11.*"
graphene-file-upload = "^1.2.2"
django-filter = "^2.3.0"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
mypy = "*"
polint = "*"
dennis = "*"
xenon = "*"
safety = "*"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-xdist = "*"
factory-boy = "*"
flake8 = "*"
flake8-pytest-style = "*"
pytest-freezegun = "*"
wemake-python-styleguide = "*"
black = "^19.10b0"
flake8-class-attributes-order = "*"
isort = ">=4.3.5 <5"

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git          # root of the project
    | \.mypy_cache
    | \.pytest_cache
    | .*\/migrations
  )/
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
