
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-18T08:52:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbbc2beb5b7bb9be83a73e97af3491dea6a53e62",
 "version": "2.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
