
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-25T06:21:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "54bd250e0059926eb4b8180c2a233cb0a1f85eb6",
 "version": "2.4.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
