# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include: [master, azure-pipelines, test-me-*]

jobs:
- job: tox
  strategy:
    matrix:
      py36:
        TOXENV: py36
        py: '3.6'
      py37:
        TOXENV: py37
        py: '3.7'
      py38:
        TOXENV: py38
        py: '3.8'
      py39:
        TOXENV: py39
        py: '3.9'
      flake8:
        TOXENV: flake8
        py: '3.9'

  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(py)

  - script: python -m pip install --upgrade tox
    displayName: install tox
  - script: tox
    displayName: run tox

#  - bash: .tox/$(TOXENV)/$(bindir)/coverage xml -o coverage.xml
#    displayName: generate coverage xml
#  - task: PublishCodeCoverageResults@1
#    inputs:
#      codeCoverageTool: cobertura
#      summaryFileLocation: coverage.xml
