version: 2.1
executors:
  toxandnode:
    working_directory: ~/project
    docker:
      - image: girder/tox-and-node
      - image: memcached
      - image: circleci/mongo:4.0-ram
      - image: rabbitmq
commands:
  tox:
    description: "Run tox"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Preinstall phantomjs to work around an npm permission issue
          command: npm install -g phantomjs-prebuilt --unsafe-perm
      - run:
          name: Run tests via tox
          # Piping through cat does less buffering of the output but can
          # consume the exit code
          command: PYTEST_ADDOPTS=--forked tox -e << parameters.env >> | cat; test ${PIPESTATUS[0]} -eq 0
  coverage:
    description: "Upload coverage"
    steps:
      - run:
          name: Install Codecov client
          command: pip install codecov==2.1.9
      - run:
          name: Upload coverage
          command: codecov --tries 10 --required --disable search pycov gcov --root project --file .tox/coverage/py_coverage.xml -f build/test/coverage/cobertura-coverage.xml

jobs:
  testdocker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the test docker
          command: docker build --force-rm -t girder/tox-and-node .
      - run:
          name: Publish the images to Docker Hub
          command: |
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push girder/tox-and-node:latest
  py36:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: py36
      - coverage
  py37:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: py37
      - coverage
  py38:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: py38
      - coverage
  py39:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: py39
      - coverage
  lint_and_docs:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: docs,flake8,lintclient,lintannotationclient
  wheels:
    executor: toxandnode
    steps:
      - checkout
      - run:
          name: Build wheels
          command: ./.circleci/make_wheels.sh
      - run:
          name: Make index file
          command: python ./.circleci/make_index.py ~/wheels
      - store_artifacts:
          path: ~/wheels
  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Setup virtual environment
          command: |
            if [ ! -d env ]; then python -m virtualenv env || python -m venv env; fi
            echo ". $CIRCLE_WORKING_DIRECTORY/env/bin/activate" >> $BASH_ENV
      - run:
          name: Install python packages
          command: pip install setuptools_scm twine
      - run:
          name: Release to PyPi
          command: ./.circleci/release_pypi.sh

workflows:
  version: 2
  ci:
    jobs:
      - testdocker:
          filters:
            branches:
              only:
                - master
                # Create a branch of this name to push to docker hub
                - testdocker
      - py36:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - py37:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - py38:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - py39:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - lint_and_docs:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - wheels:
          requires:
            - py36
            - py37
            - py38
            - py39
            - lint_and_docs
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - release:
          requires:
            - py36
            - py37
            - py38
            - py39
            - lint_and_docs
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
