[tool.poetry]
name = "smithsonian_queri"
version = "0.1.0"
description = "Python package designed to query data from the Smithsonian Open Access API using category filters based on user input."
authors = ["Alys-217 <ajz2123@tc.columbia.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.5"

[tool.poetry.dev-dependencies]
sphinx = "^3.3.1"
sphinxcontrib-napoleon = "^0.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
