[tool.poetry]
name = "algoauditor"
version = "0.0.1"
description = "Lethical AI python library"
authors = ["Amanl04 <amanlodha423@outlook.com>"]
license = "Proprietary"
homepage = "https://lethical.ai"
readme = "README.md"
maintainers = ["Aman Lodha <aman@lethical.ai>", "Akshaj Jain <akshaj@lethical.ai>"]
keywords = ["AI/ML", "discrimination", "bias", "detection", "debiasing"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.0"
numpy = "^1.19.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pdoc3 = "^0.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
