[tool.poetry]
name          = "low"
version       = "0.1.0dev"
description   = "A json parser"
license       = "MIT"
authors       = [ "Xavier Barbosa <clint.northwood@gmail.com>" ]
readme        = "README.rst"
homepage      = "https://lab.errorist.xyz/py/plum"
repository    = "https://lab.errorist.xyz/py/plum"
documentation = "https://lab.errorist.xyz/py/plum"
keywords      = [ "parser" ]
classifiers   = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

        [tool.poetry.dependencies]
        python = "^3.9"

        [tool.poetry.dev-dependencies]
        pytest         = "^6.0"
        pytest-cases   = "^3.1.1"
        pytest-cov     = "^2.10.1"
        black          = "^20.8b1"
        isort          = "^5.0"
        flake8         = "^3.0"
        flake8-bugbear = "^20.11.1"
        mypy           = "^0.790"
        flit           = "^3.0.0"

[build-system]
requires      = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"
