# Generated by Django 2.2.11 on 2020-12-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_course', '0003_auto_20201220_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionContent',
        ),
    ]
