[tool.poetry]
name = "qiyu_sso"
version = "0.1.0"
description = "SSO client from QiYuTech"
authors = ["dev <dev@qiyutech.tech>"]
readme = "README.md"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[[tool.poetry.source]]
name = "official_pypi"
url = "https://pypi.org/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"

pydantic = ">=1.7,<2"

[tool.poetry.dev-dependencies]
black = ">=20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
